Option mstored sasmstore=hx_macro;
Libname hx_macro "d:\DataQuality\05_SourceCode\01_Macro\project";
Filename macros 'd:\DataQuality\05_SourceCode\01_Macro\project\nv';
%inc macros("hx_apply_consistenza_checks.sas");
%inc macros("hx_check_created_sastables.sas");
%inc macros("hx_create_formats.sas");
%inc macros("hx_create_process_trace.sas");
%inc macros("hx_create_table_trace.sas");
%inc macros("hx_declare_ht_historical_check.sas");
%inc macros("hx_declare_ht_hist_check.sas");
%inc macros("hx_declare_ht_pr.sas");
%inc macros("hx_details_checklist.sas");
%inc macros("hx_get_col_info_dett.sas");
%inc macros("hx_get_lookup_group.sas");
%inc macros("hx_get_wkbsheets.sas");
%inc macros("hx_get_workbooks.sas");
%inc macros("hx_hist_fx_checklist.sas");
%inc macros("hx_import_cmn_metadata.sas");
%inc macros("hx_import_ldt.sas");
%inc macros("hx_import_parameters.sas");
%inc macros("hx_import_sheet.sas");
%inc macros("hx_join_from_mtd.sas");
%inc macros("hx_list_dataset_created.sas");
%inc macros("hx_lookup_value.sas");
%inc macros("hx_lookup_values_hash.sas");
%inc macros("hx_normalize_datamodel.sas");
%inc macros("hx_public_checklist.sas");
%inc macros("hx_retrieve_checks_fields.sas");
%inc macros("hx_run_checks_list.sas");
%inc macros("hx_run_lookup_rules.sas");
%inc macros("hx_set_flag_distinct.sas");
%inc macros("hx_set_portfolio.sas");
%inc macros("hx_set_portfolio_ldt.sas");
%inc macros("hx_split_lookup_checks.sas");
%inc macros("hx_sql_join.sas");
%inc macros("hx_summary_checklist.sas");
%inc macros("hx_update_tabletrace.sas");
