*==================================================================================================                                                                                                                                                             
* Cliente : AMCO SpA                                                                                                                                                                                                                                            
* Office  : CRO Portfolio Managment -> Data Verification                                                                                                                                                                                                        
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Macro name  : hx_apply_consistenza_checks                                                                                                                                                                                                                     
* Description : Applies check rearding consistenza type                                                                                                                                                                                                         
* Author      : Uriele De Piano Hexe SpA, 21 October 2020                                                                                                                                                                                                       
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* NOTE:                                                                                                                                                                                                                                                         
*==================================================================================================                                                                                                                                                             
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_apply_consistenza_checks (idAmbito          = _NULL_                                                                                                                                                                                                  
																		,tableCheck       = _NULL_                                                                                                                                                                                                                    
																		,whatDetailsCheck = _NULL_                                                                                                                                                                                                                    
																		,metadataCheck     = _NULL_                                                                                                                                                                                                                   
																		) / store secure;                                                                                                                                                                                                                                            
	%Local dsid tmpStamp                                                                                                                                                                                                                                           
	;                                                                                                                                                                                                                                                              
	%Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                                
	%Put +---[Macro: &sysmacroname.] -------------+;                                                                                                                                                                                                               
	%Put | Macro applies consistency checks	on  	|;                                                                                                                                                                                                                
	%Put | &tableCheck.;                                                                                                                                                                                                                                           
	%Put |........................................|;                                                                                                                                                                                                               
	%Put | Starting at: &tmpStamp.;                                                                                                                                                                                                                                
	%Put +----------------------------------------+;                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
	%*-- Check existence of Dataset;                                                                                                                                                                                                                               
	%If %sysfunc(exist(&tableCheck.))=0 %Then %Do;                                                                                                                                                                                                                 
		%Put +----------------------------------------------------+;                                                                                                                                                                                                  
		%Put | MSGERROR: Dataset [&tableCheck.] not exists!!!!	  |;                                                                                                                                                                                                   
		%Put +----------------------------------------------------+;                                                                                                                                                                                                  
	  %Goto uscita;	                                                                                                                                                                                                                                               
	%End;                                                                                                                                                                                                                                                          
	%*-- Check existence of Metadata Table;                                                                                                                                                                                                                        
	%If %sysfunc(exist(&metadataCheck.))=0 %Then %Do;                                                                                                                                                                                                              
		%Put +-----------------------------------------------------+;                                                                                                                                                                                                 
		%Put | MSGERROR: Metadata [&metadataCheck.] not exists!!!! |;                                                                                                                                                                                                 
		%Put +-----------------------------------------------------+;                                                                                                                                                                                                 
	  %Goto uscita;                                                                                                                                                                                                                                                
	%End;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
	Data _null_;                                                                                                                                                                                                                                                   
		%** Declare Attrib for Hash Table on Metadata;                                                                                                                                                                                                                
		%Let dsid = %sysfunc(open(&metadataCheck.));                                                                                                                                                                                                                  
		%Do _i=1 %To %Sysfunc(AttrN(&dsid.,NVARS));                                                                                                                                                                                                                   
			%Let nomeCampo = %sysfunc(varname(&dsid.,&_i.));                                                                                                                                                                                                             
			%Let typeCampo = %sysfunc(vartype(&dsid.,&_i.));                                                                                                                                                                                                             
			%Let lenCampo  = %sysfunc(varlen(&dsid.,&_i.));                                                                                                                                                                                                              
			Attrib %UnQuote(&nomeCampo.)                                                                                                                                                                                                                                 
			%If &typeCampo.=C %Then %Do;                                                                                                                                                                                                                                 
				Length=$&lenCampo.                                                                                                                                                                                                                                          
			%End;                                                                                                                                                                                                                                                        
			%Else %Do;                                                                                                                                                                                                                                                   
				Length=8                                                                                                                                                                                                                                                    
			%End;                                                                                                                                                                                                                                                        
				;                                                                                                                                                                                                                                                           
		%End;                                                                                                                                                                                                                                                         
		%Let dsid = %Sysfunc(Close(&dsid.));                                                                                                                                                                                                                          
		;                                                                                                                                                                                                                                                             
		Attrib tobecheck   Length=$1                                                                                                                                                                                                                                  
					 checkResult Length=$1                                                                                                                                                                                                                                     
					 dqListWhere Length=$5000                                                                                                                                                                                                                                  
		  ;                                                                                                                                                                                                                                                           
		idAmbito         = Upcase(Symget("idAmbito"));                                                                                                                                                                                                                
		dqListWhere      = '1';                                                                                                                                                                                                                                       
		whatDetailsCheck = Upcase(Symget("whatDetailsCheck"));                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                
		If whatDetailsCheck ^= "_NULL_" Then                                                                                                                                                                                                                          
			dqListWhere = catx(' ',dqListWhere,"and Upcase(detailCheck)=:",cats("'",Upcase(whatDetailsCheck),"'"));                                                                                                                                                      
	  If idAmbito ^= "_NULL_" Then                                                                                                                                                                                                                                 
	 		dqListWhere = Strip(dqListWhere)||" And Upcase(idAmbito)='"||Strip(idAmbito)||"'";                                                                                                                                                                          
                                                                                                                                                                                                                                                                
		Declare hash htChecks(dataset:cats("&metadataCheck. (Where=(",dqListWhere,"))")                                                                                                                                                                               
							 ,ordered:"yes"                                                                                                                                                                                                                                          
							 ,multidata:"yes");                                                                                                                                                                                                                                      
			htChecks.defineKey("idAmbito","campoTecnico");                                                                                                                                                                                                               
			htChecks.defineData("idRule","detailCheck");                                                                                                                                                                                                                 
			htChecks.defineDone();                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
		tableData = Symget("tableCheck");                                                                                                                                                                                                                             
  	dsid      = Open(tableData);                                                                                                                                                                                                                                 
  	Do While (fetch(dsid)=0);                                                                                                                                                                                                                                    
			%*-- Cycle on variables;                                                                                                                                                                                                                                     
			Do _idVar=1 To Attrn(dsid,"NVARS");                                                                                                                                                                                                                          
				nomeCampo = lowcase(varname(dsid,_idVar));                                                                                                                                                                                                                  
				tobecheck = ifc(htChecks.check(key:idAmbito,key:nomeCampo)=0,'Y','N');                                                                                                                                                                                      
				If tobecheck='Y' Then Do;                                                                                                                                                                                                                                   
					%*-- Get checks;                                                                                                                                                                                                                                           
					_rcFind = htChecks.find(key:idAmbito,key:nomeCampo);                                                                                                                                                                                                       
					If lowcase(detailCheck)=:"missing" Then Do;                                                                                                                                                                                                                
						checkResult = hx_check_missing(dsid,nomeCampo,'N');                                                                                                                                                                                                       
						*Do While(tobecheck='Y');                                                                                                                                                                                                                                 
							*Put idRule= nomeCampo= checkResult= ;                                                                                                                                                                                                                   
							tobecheck = ifc(htChecks.find_next(key:idAmbito,key:nomeCampo)=0,'Y','N');                                                                                                                                                                               
						*End;                                                                                                                                                                                                                                                     
					End;                                                                                                                                                                                                                                                       
				End;                                                                                                                                                                                                                                                        
			End; *-- End of cycle variables;                                                                                                                                                                                                                             
		End; *-- End of Fetch table;                                                                                                                                                                                                                                  
  	dsid = close(dsid);                                                                                                                                                                                                                                          
	Run;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
	%Uscita:                                                                                                                                                                                                                                                       
		%Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
		%Put +---[Macro: &sysmacroname.] -------------+;                                                                                                                                                                                                              
		%Put | Ended at: &tmpStamp.;                                                                                                                                                                                                                                  
		%Put +----------------------------------------+;                                                                                                                                                                                                              
%Mend;                                                                                                                                                                                                                                                          
