*============================================================================================                                                                                                                                                                   
* Client Name: AMCO SpA                                                                                                                                                                                                                                         
* Project    : Framework di Data Verification                                                                                                                                                                                                                   
*--------------------------------------------------------------------------------------------                                                                                                                                                                   
* Program name: hx_create_process_trace                                                                                                                                                                                                                         
* Author      : Uriele De Piano Hexe SpA 02 October 2020                                                                                                                                                                                                        
* Description : Creation of process trace table                                                                                                                                                                                                                 
*--------------------------------------------------------------------------------------------                                                                                                                                                                   
* NOTE:                                                                                                                                                                                                                                                         
*============================================================================================                                                                                                                                                                   
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_create_process_trace(dataTrace=_NULL_ ) / store secure ;                                                                                                                                                                                              
	%local folderTrace                                                                                                                                                                                                                                             
	   ;                                                                                                                                                                                                                                                           
	%Let folderTrace = %sysfunc(pathName(%qscan(&dataTrace.,1,%NrQuote(.))));                                                                                                                                                                                      
	%Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
	%if %sysfunc(exist(&dataTrace.))=0 %then %do;                                                                                                                                                                                                                  
		%Put +-- [Macro: &sysmacroname.] --------------------------------------------------;                                                                                                                                                                          
		%Put | Create Table Trace                                           							 ;                                                                                                                                                                                 
  	%Put |   Data trace : &dataProvider. 		     		                                   ;                                                                                                                                                                           
		%Put |   Folder     : &folderTrace.                                                ;                                                                                                                                                                          
		%Put |.............................................................................;                                                                                                                                                                          
		%Put | Starting at: &tmpStamp.																										 ;                                                                                                                                                                                                    
		%Put +-----------------------------------------------------------------------------;                                                                                                                                                                          
                                                                                                                                                                                                                                                                
		data &dataTrace. ;                                                                                                                                                                                                                                            
			Attrib  idTransaction Length=$25 	Label="Id transaction" format=$25.                                                                                                                                                                                         
							dta_reference	Length=8		Label="Reference date" format=ddmmyy10.                                                                                                                                                                                          
							cod_ist				Length=8		Label="Code Istitute"  format=Z5.                                                                                                                                                                                                   
						  timeStamp			Length=8		Label="Timestamp" 		 format=datetime.                                                                                                                                                                                             
							dataProvider  Length=$15 	Label="Data provider"	 format=$15.                                                                                                                                                                                             
							sourceCode  	Length=$40	Label="Source code"		 format=$40.                                                                                                                                                                                                
							stepCode 			Length=$256	Label="Step code"			 format=$256.                                                                                                                                                                                                
						  rcCode				Length=8		Label="Return Code"		 format=12.                                                                                                                                                                                                    
						  msgCode		    Length=$256	Label="Message code"	 format=$256.                                                                                                                                                                                             
							;                                                                                                                                                                                                                                                        
			Delete;                                                                                                                                                                                                                                                      
		run;                                                                                                                                                                                                                                                          
	%end;                                                                                                                                                                                                                                                          
%mend;                                                                                                                                                                                                                                                          
