%Macro hx_get_wkbsheets(wkbFolder=,wkbName=,dsSheetList=_dsListOfSheet ) / store secure ;                                                                                                                                                                       
	Libname wkb excel "&wkbFolder./&wkbName." mixed=yes;                                                                                                                                                                                                           
	Proc Sql;                                                                                                                                                                                                                                                      
		Create Table &dsSheetList. As                                                                                                                                                                                                                                 
			Select  "&wkbFolder." as workBookFolder Length=256                                                                                                                                                                                                           
				   ,"&wkbName." as workBookName Length=256                                                                                                                                                                                                                  
				   ,memname Length=100                                                                                                                                                                                                                                      
			from sashelp.vtable                                                                                                                                                                                                                                          
			where libname = "WKB" and lowcase(memname) not contains "filter"                                                                                                                                                                                             
		;                                                                                                                                                                                                                                                             
	Quit;                                                                                                                                                                                                                                                          
	Libname wkb clear;                                                                                                                                                                                                                                             
%mend;                                                                                                                                                                                                                                                          
/*                                                                                                                                                                                                                                                              
%hx_get_wkbsheets(wkbFolder=D:\dataquality\01_sourcedata\mps                                                                                                                                                                                                    
				 ,wkbName=25.4.2_HYD_201912_INFREQ_POST_IN_OUT_NEW.xlsx                                                                                                                                                                                                     
				  ,dsSheetList=_dsListOfSheet);                                                                                                                                                                                                                             
*/                                                                                                                                                                                                                                                              
