%Macro hx_get_workbooks(folder=,dsListWKb=_listOfWorbooks ) / store secure ;                                                                                                                                                                                    
	Data &dsListWKb. (Keep=folder idwkbFile wkbFile);                                                                                                                                                                                                              
		Attrib 	folder    Length=$256                                                                                                                                                                                                                                 
				idwkbFile Length=8                                                                                                                                                                                                                                          
				wkbFile   Length=$256                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
		   ;                                                                                                                                                                                                                                                          
		folder = Symget("folder");                                                                                                                                                                                                                                    
		cmdWin = cats('dir /b "',folder,'"');                                                                                                                                                                                                                         
		Put cmdWin=;                                                                                                                                                                                                                                                  
		rc  = filename("dlist",cmdWin,"pipe");                                                                                                                                                                                                                        
		fid = fopen("dlist",'s');                                                                                                                                                                                                                                     
		Call missing(idwkbFile);                                                                                                                                                                                                                                      
		Do While (fread(fid)=0);                                                                                                                                                                                                                                      
			rc  = fget(fid,wkbFile,256);                                                                                                                                                                                                                                 
			wkbFile = compbl(wkbFile);                                                                                                                                                                                                                                   
			put wkbFile=;                                                                                                                                                                                                                                                
			if prxmatch("/.xls/i",wkbFile)>0 Then Do;                                                                                                                                                                                                                    
				idwkbFile = sum(idwkbFile,1);                                                                                                                                                                                                                               
				Output;                                                                                                                                                                                                                                                     
			End;                                                                                                                                                                                                                                                         
		End;                                                                                                                                                                                                                                                          
		fid = fclose(fid);                                                                                                                                                                                                                                            
	Run;                                                                                                                                                                                                                                                           
%Mend;                                                                                                                                                                                                                                                          
