*==================================================================================================                                                                                                                                                             
* Cliente : AMCO SpA                                                                                                                                                                                                                                            
* Office  : CRO Portfolio Managment -> Data Verification                                                                                                                                                                                                        
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Macro name  : hx_lookup_values_hash                                                                                                                                                                                                                           
* Description : Starting from a common keys, it produces sas statment on hash table using                                                                                                                                                                       
*								Table contains attrib statment and declare hash statment and find statment                                                                                                                                                                             
* Author      : Uriele De Piano Hexe SpA, 18 November 2020                                                                                                                                                                                                      
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Parameter:                                                                                                                                                                                                                                                    
*    1) sourceKeys   : keys from (<libname.sourceTable>@fieldKey1-fieldKey<N>) Each field will be separated by -                                                                                                                                                
*    2) sourceWcls   : where clause  not mandatory default value = _NULL_                                                                                                                                                                                       
*		 3) targetKeys   : keys on (<libname.tableName>@fieldKey1-fieldKey<N>) Each field will be separated by -                                                                                                                                                     
*    4) targetWcls   : where clause not mandatory default value = _NULL_                                                                                                                                                                                        
*    5) targetData   : list of fields to return not mandatory default value = _NULL_                                                                                                                                                                            
*											 format (fieldData1-fieldData<N>)                                                                                                                                                                                                                   
*		 6) idLookupRule : Id rule (used to create a flag match(nomatch)                                                                                                                                                                                             
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Output                                                                                                                                                                                                                                                        
*   Macro returns a dataset named work.hx_lookup_values_log containing a summary logs                                                                                                                                                                           
*		Data model                                                                                                                                                                                                                                                   
*				- timestamp                                                                                                                                                                                                                                                
*				- idRule (default LKP1)                                                                                                                                                                                                                                    
*				- source table (containg keys, too)                                                                                                                                                                                                                        
*				- whereclause                                                                                                                                                                                                                                              
*				- target table (contains keys and returned data. Returned data fields will be enclosed in "[]")                                                                                                                                                            
*				- whereclause                                                                                                                                                                                                                                              
*				- status (LOOKUP-GO,LOOKUP_STOPPED)                                                                                                                                                                                                                        
*				- detailsStatus (Details status. Describe reason in case of LOOKUP_STOPPED)                                                                                                                                                                                
*				- Dataset sas containing statment sas                                                                                                                                                                                                                      
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* NOTE: Statment about hash table will be write in dataset sas                                                                                                                                                                                                  
*==================================================================================================                                                                                                                                                             
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_lookup_values_hash(sourceKeys = _NULL_                                                                                                                                                                                                                
													   ,sourceKeep = _NULL_                                                                                                                                                                                                                            
														 ,sourceWcls	= _NULL_                                                                                                                                                                                                                             
														 ,targetKeys = _NULL_                                                                                                                                                                                                                             
														 ,targetWcls = _NULL_                                                                                                                                                                                                                             
														 ,targetKeep = _NULL_                                                                                                                                                                                                                             
														 ,dsOutput 	= _NULL_                                                                                                                                                                                                                              
														 ,idLookup 	= _NULL_                                                                                                                                                                                                                              
														 ,libCode   = work) / store secure ;                                                                                                                                                                                                                              
	%Local timeStamp wlcsDate dsid dsidDP _dsCode _statment _dsStatment                                                                                                                                                                                            
		;                                                                                                                                                                                                                                                             
	%Let timeStamp   = %sysfunc(datetime());                                                                                                                                                                                                                       
	%Let _dsStatment = %UnQuote(&libCode.)._hash_dynamic_code_&idLookup.;                                                                                                                                                                                          
	%Put +----[macro=&sysmacroname.] ----------+;                                                                                                                                                                                                                  
	%Put | Macro applies lookup rule					 |;                                                                                                                                                                                                                       
	%Put | Create &_dsStatment.								 |;                                                                                                                                                                                                                         
	%Put | ....................................|;                                                                                                                                                                                                                  
	%Put | Started at: %sysfunc(putn(&timeStamp.,datetime.));                                                                                                                                                                                                      
	%Put +-------------------------------------+;                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
	Data _null_;                                                                                                                                                                                                                                                   
		Attrib idLookup     Length=$20                                                                                                                                                                                                                                
					 idStatment	  Length=8                                                                                                                                                                                                                                     
					 typeStatment Length=$20                                                                                                                                                                                                                                   
					 statment     Length=$500                                                                                                                                                                                                                                  
					 flg_idLookup Length=$32                                                                                                                                                                                                                                   
					 ;                                                                                                                                                                                                                                                         
		Retain idLookup "&idLookup." dsOutput "&dsOutput."                                                                                                                                                                                                            
				;                                                                                                                                                                                                                                                           
		Declare hash htcode(multidata:"yes",ordered:"yes");                                                                                                                                                                                                           
			htcode.defineKey("idLookup","typeStatment","idStatment");                                                                                                                                                                                                    
			htcode.defineData("idLookup","idStatment","typeStatment","statment");                                                                                                                                                                                        
			htcode.defineDone();                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
		Attrib 	sourceTable Length=$40                                                                                                                                                                                                                                
						sourceKeys 	Length=$1000                                                                                                                                                                                                                                  
						sourceKeep	Length=$1000                                                                                                                                                                                                                                   
						wclsSource	Length=$500                                                                                                                                                                                                                                    
						lookupTable Length=$40                                                                                                                                                                                                                                    
						lookupKeys 	Length=$1000                                                                                                                                                                                                                                  
						lookupData	Length=$1000                                                                                                                                                                                                                                   
						wclsTarget	Length=$500                                                                                                                                                                                                                                    
						stmtMissing Length=$1000                                                                                                                                                                                                                                  
			;                                                                                                                                                                                                                                                            
	                                                                                                                                                                                                                                                               
		sourceTable = scan("&sourceKeys.",1,'@');                                                                                                                                                                                                                     
		sourceKeys  = scan("&sourceKeys.",2,'@');                                                                                                                                                                                                                     
		sourceKeep  = strip("&sourceKeep.");                                                                                                                                                                                                                          
		wclsSource  = Strip(Symget("sourceWcls"));                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
		lookupTable = scan("&targetKeys.",1,'@');                                                                                                                                                                                                                     
		lookupKeys  = scan("&targetKeys.",2,'@');                                                                                                                                                                                                                     
		wclsTarget  = Strip(Symget("targetWcls"));                                                                                                                                                                                                                    
		lookupData  = Strip(Symget("targetKeep"));                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
		Call Missing(idStatment,typeStatment);                                                                                                                                                                                                                        
		%*-- Compose statment sas;                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
		%*-- Write data/set statment;                                                                                                                                                                                                                                 
		statment = catx(' ',"Data",dsOutput,';');                                                                                                                                                                                                                     
		Link writeCode;                                                                                                                                                                                                                                               
		statment = catx(' ',"set",sourceTable);                                                                                                                                                                                                                       
		%*-- Check if keep statment o where statment has been passed;                                                                                                                                                                                                 
		If Upcase(sourceKeep) not In ("_NULL_",' ','*') Or wclsSource not In ("_NULL_",' ') Then Do;                                                                                                                                                                  
			statment = catx(' ',statment,'(');                                                                                                                                                                                                                           
			If Upcase(sourceKeep) not In ("_NULL_",' ','*') Then                                                                                                                                                                                                         
				statment = catx(' ',statment,"keep=",tranwrd(sourceKeep,'-',' '));                                                                                                                                                                                          
			If wclsSource not In ("_NULL_",' ') Then                                                                                                                                                                                                                     
				statment = catx(' ',statment,"where=(",wclsSource,")");                                                                                                                                                                                                     
			statment = catx(' ',statment,')');                                                                                                                                                                                                                           
			Link writeCode;                                                                                                                                                                                                                                              
		End;                                                                                                                                                                                                                                                          
		statment = ";";                                                                                                                                                                                                                                               
		Link writeCode;                                                                                                                                                                                                                                               
		%*-- Write attrib statment;                                                                                                                                                                                                                                   
		typeStatment = "attrib";                                                                                                                                                                                                                                      
		flg_idLookup = cats("flglkp_",Symget("idLookup"));                                                                                                                                                                                                            
		oss_idLookup = cats("osslkp_",Symget("idLookup"));                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
		statment = catx(' ',"Attrib",flg_idLookup,"Length=$3",catx(' ',"Label='Lookup on",lookupTable,"'"),';');                                                                                                                                                      
		Link writeCode;                                                                                                                                                                                                                                               
		statment = catx(' ',"Attrib",oss_idLookup,"Length=8",catx(' ',"Label='Sequence lookup on",lookupTable,"'"),';');                                                                                                                                              
		Link writeCode;                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
		stmtMissing = cats("Call Missing(",oss_idLookup);                                                                                                                                                                                                             
		%*- Compose attrib and call missing statment;                                                                                                                                                                                                                 
		If Upcase(lookupData) not in ("_NULL_") and not missing(lookupData) Then Do;                                                                                                                                                                                  
			nDefineData = Sum(count(lookupData,'-'),1);                                                                                                                                                                                                                  
			%*-- Open lookup table to retrieve information about data returned;                                                                                                                                                                                          
			dsidLkp = open(lookupTable);                                                                                                                                                                                                                                 
			Do _v=1 To nDefineData;                                                                                                                                                                                                                                      
				colName     = strip(scan(lookupData,_v,'-'));                                                                                                                                                                                                               
				whereIs     = varnum(dsidLkp,colName);                                                                                                                                                                                                                      
				stmtMissing = cats(stmtMissing,',',colName);                                                                                                                                                                                                                
				statment    = catx(' ',"Attrib",colName);                                                                                                                                                                                                                   
				If vartype(dsidLkp,whereIs)=:'C' Then                                                                                                                                                                                                                       
					statment = catx(' ',statment,cats("Length=$",Put(varLen(dsidLkp,whereIs),18.)));                                                                                                                                                                           
				Else                                                                                                                                                                                                                                                        
					statment = catx(' ',statment,"Length=8");                                                                                                                                                                                                                  
				If Not missing(varLabel(dsidLkp,whereIs)) Then                                                                                                                                                                                                              
					statment = catx(' ',statment,cats("Label='",varLabel(dsidLkp,whereIs),"'"));                                                                                                                                                                               
                                                                                                                                                                                                                                                                
				If Not missing(varFmt(dsidLkp,whereIs)) Then                                                                                                                                                                                                                
					statment = catx(' ',statment,cats("Format=",varFmt(dsidLkp,whereIs)));                                                                                                                                                                                     
				statment  = cats(statment,';');                                                                                                                                                                                                                             
				Link writeCode;                                                                                                                                                                                                                                             
			End;                                                                                                                                                                                                                                                         
		End;                                                                                                                                                                                                                                                          
		stmtMissing = cats(stmtMissing,");");                                                                                                                                                                                                                         
		typeStatment = "hash";                                                                                                                                                                                                                                        
		Link writeHash;                                                                                                                                                                                                                                               
		Return;                                                                                                                                                                                                                                                       
		WRITEHASH:                                                                                                                                                                                                                                                    
			*-- Write Hash statment;                                                                                                                                                                                                                                     
			statment = cats("Declare hash htLookup(dataset:'",lookupTable);                                                                                                                                                                                              
			If Upcase(wclsTarget) not in ("_NULL_") And not missing(wclsTarget) Then                                                                                                                                                                                     
				statment = catx(' ',statment,cats("(Where=(",wclsTarget,"))"));                                                                                                                                                                                             
			statment = cats(statment,"',ordered:'yes',multidata:'yes');");                                                                                                                                                                                               
			Link writeCode;                                                                                                                                                                                                                                              
			*-- Close declare statment;                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
			*-- Open defineKey statment;                                                                                                                                                                                                                                 
			statment = Compress(cats("htLookup.defineKey('",tranwrd(lookupKeys,'-',"','"),"');"));                                                                                                                                                                       
			Link writeCode;                                                                                                                                                                                                                                              
			*-- Close defineKey statment;                                                                                                                                                                                                                                
			If Upcase(lookupData) not in ("_NULL_") and not missing(lookupData) Then Do;                                                                                                                                                                                 
				*-- Open defineData statment;                                                                                                                                                                                                                               
				statment = Compress(cats("htLookup.defineData('",tranwrd(lookupData,'-',"','"),"');"));                                                                                                                                                                     
				Link writeCode;                                                                                                                                                                                                                                             
				*-- Close defineData statment;                                                                                                                                                                                                                              
			End;                                                                                                                                                                                                                                                         
			*-- Open defineDone statment;                                                                                                                                                                                                                                
			statment = "htLookup.defineDone();";                                                                                                                                                                                                                         
			Link writeCode;                                                                                                                                                                                                                                              
			*-- Close defineDone statment;                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
			*-- Write Call Missing statment;                                                                                                                                                                                                                             
			statment   = stmtMissing;                                                                                                                                                                                                                                    
			Link writeCode;                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                
			*-- Open find o checkStatment statment;                                                                                                                                                                                                                      
			typeMethod = 'C';                                                                                                                                                                                                                                            
			If Upcase(lookupData) not in ("_NULL_") and not missing(lookupData) Then Do;                                                                                                                                                                                 
				typeMethod='F';                                                                                                                                                                                                                                             
				statment = cats(flg_idLookup,"=ifc(htLookup.find(");                                                                                                                                                                                                        
			End;                                                                                                                                                                                                                                                         
			Else                                                                                                                                                                                                                                                         
				statment = cats(flg_idLookup,"=ifc(htLookup.check(");                                                                                                                                                                                                       
			sep   = ' ';                                                                                                                                                                                                                                                 
			nKeys = Sum(count(sourceKeys,'-'),1);                                                                                                                                                                                                                        
			Do _v=1 To nKeys;                                                                                                                                                                                                                                            
				colName  = Strip(Scan(sourceKeys,_v,'-'));                                                                                                                                                                                                                  
				statment = cats(statment,sep,"key:",colName);                                                                                                                                                                                                               
				sep = ',';                                                                                                                                                                                                                                                  
			End;                                                                                                                                                                                                                                                         
			statment = cats(statment,")=0,'Y','N');");                                                                                                                                                                                                                   
			Link writeCode;                                                                                                                                                                                                                                              
			*-- Write statment to raise oss_idLookup;                                                                                                                                                                                                                    
			statment = catx(' ',"if",flg_idLookup,"='Y' Then",oss_idLookup,"=sum(",oss_idLookup,",1);");                                                                                                                                                                 
			Link writeCode;                                                                                                                                                                                                                                              
			statment = "Output;";                                                                                                                                                                                                                                        
			Link writeCode;                                                                                                                                                                                                                                              
			%*-- Richiama il metodo find_next();                                                                                                                                                                                                                         
			statment = cats("Do While (",flg_idLookup,"='Y');");                                                                                                                                                                                                         
			Link writeCode;                                                                                                                                                                                                                                              
			%*-- Compose find_next statment;                                                                                                                                                                                                                             
	  	statment = cats(flg_idLookup,"=ifc(htLookup.find_next(");                                                                                                                                                                                                   
		  nKeys 	 = Sum(count(sourceKeys,'-'),1);                                                                                                                                                                                                                     
			sep      = ' ';                                                                                                                                                                                                                                              
  		Do _v=1 To nKeys;                                                                                                                                                                                                                                           
			  colName  = Strip(Scan(sourceKeys,_v,'-'));                                                                                                                                                                                                                 
			  statment = cats(statment,sep,"key:",colName);                                                                                                                                                                                                              
			  sep = ',';                                                                                                                                                                                                                                                 
			End;                                                                                                                                                                                                                                                         
			statment = cats(statment,")=0,'Y','N');");                                                                                                                                                                                                                   
			Link writeCode;                                                                                                                                                                                                                                              
			*-- Compose find_next statment end;                                                                                                                                                                                                                          
			statment = catx(' ',"if",flg_idLookup,"='Y' Then Do;",oss_idLookup,"=sum(",oss_idLookup,",1);Output;End;");                                                                                                                                                  
			Link writeCode;                                                                                                                                                                                                                                              
			statment = "End;";                                                                                                                                                                                                                                           
			Link writeCode;                                                                                                                                                                                                                                              
			statment = "run;";                                                                                                                                                                                                                                           
			Link writeCode;                                                                                                                                                                                                                                              
			*-- Close find o checkStatment statment;                                                                                                                                                                                                                     
		RETURN;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
		WRITECODE:                                                                                                                                                                                                                                                    
			idStatment = Sum(idStatment,1);                                                                                                                                                                                                                              
			rc         = htcode.add();                                                                                                                                                                                                                                   
			rc         = htCode.output(dataset:"&_dsStatment.");                                                                                                                                                                                                         
		RETURN;                                                                                                                                                                                                                                                       
	Run;                                                                                                                                                                                                                                                           
						                                                                                                                                                                                                                                                          
	%Let _dsCode = %sysfunc(open(&_dsStatment.));                                                                                                                                                                                                                  
	%Do %While (%sysfunc(fetch(&_dscode.))=0);                                                                                                                                                                                                                     
		%Let _statment = %sysfunc(getvarc(&_dscode.,%sysfunc(varnum(&_dscode.,statment))));                                                                                                                                                                           
		%UnQuote(&_statment.)                                                                                                                                                                                                                                         
	%End;                                                                                                                                                                                                                                                          
	%Let _dsCode = %sysfunc(close(&_dscode.));                                                                                                                                                                                                                     
	Data _null_;                                                                                                                                                                                                                                                   
		%*-- Declare hash table regarding process trace;                                                                                                                                                                                                              
		%hx_declare_ht_pr(htTable=&processTrace.);                                                                                                                                                                                                                    
		sourceCode    = symget("sysmacroname");                                                                                                                                                                                                                       
		stepCode      = catx(' ',"Esecuzione della lookup:",idLookup);                                                                                                                                                                                                
		Call Missing(rcCode,msgCode);                                                                                                                                                                                                                                 
		dsOutput = "&dsOutput.";                                                                                                                                                                                                                                      
		If exist(dsOutput) Then Do;                                                                                                                                                                                                                                   
			nrec 		= hx_get_nobs(dsOutput);                                                                                                                                                                                                                              
			msgCode = catx(' ',dsOutput,"has been created with",put(nrec,commax18.),"records");                                                                                                                                                                          
			rcCode  = 1;                                                                                                                                                                                                                                                 
		End;                                                                                                                                                                                                                                                          
		Else Do;                                                                                                                                                                                                                                                      
			nrec 		= hx_get_nobs(dsOutput);                                                                                                                                                                                                                              
			msgCode = catx(' ',dsOutput,"has not been created. Please see log");                                                                                                                                                                                         
			rcCode  = 0;                                                                                                                                                                                                                                                 
		End;                                                                                                                                                                                                                                                          
		rc = ht.output(dataset:"&processTrace.");                                                                                                                                                                                                                     
	Run;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
	%Uscita:                                                                                                                                                                                                                                                       
		%Let timeStamp = %sysfunc(datetime());                                                                                                                                                                                                                        
		%Put +----[macro=&sysmacroname.] ----------+;                                                                                                                                                                                                                 
		%Put | Macro applies lookup rule					 |;                                                                                                                                                                                                                      
		%Put | ....................................|;                                                                                                                                                                                                                 
		%Put | Started at: %sysfunc(putn(&timeStamp.,datetime.));                                                                                                                                                                                                     
		%Put +-------------------------------------+;                                                                                                                                                                                                                 
%Mend;                                                                                                                                                                                                                                                          
