*==================================================================================================                                                                                                                                                             
* Cliente : AMCO SpA                                                                                                                                                                                                                                            
* Office  : CRO Portfolio Managment -> Data Verification                                                                                                                                                                                                        
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Macro name  : hx_public_checklist                                                                                                                                                                                                                             
* Description : Historicize checklist rules.                                                                                                                                                                                                                    
* Author      : Uriele De Piano Hexe SpA, 18 January 2021                                                                                                                                                                                                       
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Parameter:                                                                                                                                                                                                                                                    
*    	1) checksOutput -> Results of check lists created by hx_details_checklist                                                                                                                                                                                 
*                                                                                                                                                                                                                                                               
* In addition macro uses, also macro variables declared and used in hx_run_check_list                                                                                                                                                                           
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Output                                                                                                                                                                                                                                                        
*  - Temporary summary checks                                                                                                                                                                                                                                   
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* NOTE: Macro can be called only after hx_details_checklist execution                                                                                                                                                                                           
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
*==================================================================================================                                                                                                                                                             
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_public_checklist(checksOutput=_null_ ) / store secure ;                                                                                                                                                                                               
	%Local _tmpStamp _wclsDeleteBeforeApp _wclsDeleteHist _dsid                                                                                                                                                                                                    
			;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
	%Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
	%Put +---[Macro: &sysmacroname.] -------------+;                                                                                                                                                                                                               
	%Put | Historicize results of checklist.			|;                                                                                                                                                                                                                  
	%Put |........................................|;                                                                                                                                                                                                               
	%Put | Started at: &_tmpStamp.;                                                                                                                                                                                                                                
	%Put +----------------------------------------+;                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
	%Let _wclsDeleteBeforeApp=1;                                                                                                                                                                                                                                   
	%If %symExist(cod_ist) %Then %Do;                                                                                                                                                                                                                              
		%Let _wclsDeleteBeforeApp = %NrQuote(cod_ist = &cod_ist.);                                                                                                                                                                                                    
	%End;                                                                                                                                                                                                                                                          
	%Let _wclsDeleteBeforeApp = %NrQuote(&_wclsDeleteBeforeApp. And idAmbito="&idAmbito." And idTransaction = Strip%("&idTrasaction."%) And DataProvider In %("CMN","&dataProvider."%) And dta_reference="&dta_reference."d);                                      
                                                                                                                                                                                                                                                                
	%If %sysfunc(exist(&checksOutput.)) %Then %Do;                                                                                                                                                                                                                 
		%*-- Macro: histchecks declared inside autoexec;                                                                                                                                                                                                              
		Proc Sql;                                                                                                                                                                                                                                                     
			Delete From &histchecks.                                                                                                                                                                                                                                     
				Where &_wclsDeleteBeforeApp.                                                                                                                                                                                                                                
					;                                                                                                                                                                                                                                                          
			%If %sysfunc(exist(&histCtchecks.)) %Then %Do;                                                                                                                                                                                                               
				Delete From &histCtchecks.                                                                                                                                                                                                                                  
					Where &_wclsDeleteBeforeApp.                                                                                                                                                                                                                               
						;                                                                                                                                                                                                                                                         
			%End;                                                                                                                                                                                                                                                        
		Quit;                                                                                                                                                                                                                                                         
		Data &histchecks.; Set &histchecks.                                                                                                                                                                                                                           
													&checksOutput.;                                                                                                                                                                                                                                    
		Run;                                                                                                                                                                                                                                                          
		Data &histCtchecks.; Set                                                                                                                                                                                                                                      
		%If %sysfunc(exist(&histCtchecks.)) %Then %Do;                                                                                                                                                                                                                
				&histCtchecks.                                                                                                                                                                                                                                              
		%End;                                                                                                                                                                                                                                                         
				&_dsFxCampiTecn.;                                                                                                                                                                                                                                           
		Run;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
		%Let _wclsDeleteHist=1;                                                                                                                                                                                                                                       
		%If %symExist(cod_ist) %Then %Do;                                                                                                                                                                                                                             
			%Let _wclsDeleteHist = %NrQuote(cod_ist = &cod_ist.);                                                                                                                                                                                                        
		%End;			                                                                                                                                                                                                                                                      
		%Let _wclsDeleteHist = %NrQuote(&_wclsDeleteHist. And idAmbito="&idAmbito." And DataProvider In %("&dataProvider."%) And dta_reference="&dta_reference."d);                                                                                                   
		%*-- Macro dsHistRepChecks declared inside autoexec;                                                                                                                                                                                                          
		%*-- Check existence varname cod_portafoglio_gest des_portafoglio_gest;                                                                                                                                                                                       
		/*                                                                                                                                                                                                                                                            
		Data _null_;                                                                                                                                                                                                                                                  
			Attrib varname		Length=$80                                                                                                                                                                                                                                   
						 varAttrib	Length=$256                                                                                                                                                                                                                                    
					;                                                                                                                                                                                                                                                          
			Declare hash ht();	                                                                                                                                                                                                                                          
				ht.defineKey("varname");                                                                                                                                                                                                                                    
				ht.defineData("varname","varAttrib");                                                                                                                                                                                                                       
				ht.defineDone();                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
			%*-- Check datamodel;                                                                                                                                                                                                                                        
			_dsid 	= open("&checksOutput.");                                                                                                                                                                                                                             
			_dsHist	= open("&dsHistRepChecks.");                                                                                                                                                                                                                         
			_statment = ' ';                                                                                                                                                                                                                                             
			Do _v=1 to AttrN(_dsid,"NVARS");                                                                                                                                                                                                                             
				varname = varname(_dsid,_v);                                                                                                                                                                                                                                
				If varnum(_dsHist,varname)<=0 Then Do;                                                                                                                                                                                                                      
					varAttrib = _statment||' '||Strip(varname);                                                                                                                                                                                                                
					varAttrib = ifc(varType(_dsid,_v)=:'C',catx(' ',varAttrib,"Varchar(",put(varLen(_dsid,_v),12.),')')                                                                                                                                                        
																								,catx(' ',varAttrib,"Num")                                                                                                                                                                                                              
													);                                                                                                                                                                                                                                                 
					if not missing(varfmt(_dsid,_v)) then                                                                                                                                                                                                                      
						varAttrib = catx(' ',varAttrib,"format =",varfmt(_dsid,_v));                                                                                                                                                                                              
					_rcHt = ht.add();                                                                                                                                                                                                                                          
					_statment = ',';                                                                                                                                                                                                                                           
				End;                                                                                                                                                                                                                                                        
			End;                                                                                                                                                                                                                                                         
			If ht.num_items>0 Then _rcHT =  ht.output(dataset:"work_histChecksModel");                                                                                                                                                                                   
		Run;                                                                                                                                                                                                                                                          
		*/                                                                                                                                                                                                                                                            
		Proc Sql;                                                                                                                                                                                                                                                     
		/*                                                                                                                                                                                                                                                            
			%if %sysfunc(exist(work._histChecksModel)) %then %do;                                                                                                                                                                                                        
				Alter table &dsHistRepChecks. Add                                                                                                                                                                                                                           
				%Let _dsid = %sysfunc(open(work._histChecksModel));                                                                                                                                                                                                         
				%Do %While (%sysfunc(fetch(&_dsid.))=0);                                                                                                                                                                                                                    
					%Let _varName = %sysfunc(getvarc(_dsid,%sysfunc(varnum(&_dsid.,varname))));                                                                                                                                                                                
					%Let _varStmt = %sysfunc(getvarc(_dsid,%sysfunc(varnum(&_dsid.,varAttrib))));                                                                                                                                                                              
					%UnQuote(&_varName.) %UnQuote(&_varStmt.)                                                                                                                                                                                                                  
				%End;                                                                                                                                                                                                                                                       
				;                                                                                                                                                                                                                                                           
				%Let _dsid = %sysfunc(close(&_dsid.));                                                                                                                                                                                                                      
			%end;                                                                                                                                                                                                                                                        
		*/                                                                                                                                                                                                                                                            
			Delete From &dsHistRepChecks. Where &_wclsDeleteHist.;                                                                                                                                                                                                       
			/*                                                                                                                                                                                                                                                           
			%if %sysfunc(exist(work._histChecksModel)) %then %do;                                                                                                                                                                                                        
				Drop Table work._histChecksModel;                                                                                                                                                                                                                           
			%End;                                                                                                                                                                                                                                                        
			*/                                                                                                                                                                                                                                                           
		Quit;                                                                                                                                                                                                                                                         
		Data &dsHistRepChecks.;                                                                                                                                                                                                                                       
			Set &dsHistRepChecks. (in=a)                                                                                                                                                                                                                                 
					&checksOutput. (in=b);                                                                                                                                                                                                                                     
			If b Then Do;                                                                                                                                                                                                                                                
				ruleFlag  = ifn(eseguito='Y',1,0);                                                                                                                                                                                                                          
				tableName = Scan(tableName,2,'.');                                                                                                                                                                                                                          
			End;                                                                                                                                                                                                                                                         
		Run;                                                                                                                                                                                                                                                          
	%End;                                                                                                                                                                                                                                                          
%Mend;                                                                                                                                                                                                                                                          
/*                                                                                                                                                                                                                                                              
%Let _libout 				= datichk;                                                                                                                                                                                                                                     
%Let _dsOutChecks 	= DWH_COUNTERPARTIES;                                                                                                                                                                                                                        
%Let idAmbito				= A;                                                                                                                                                                                                                                           
%Let dsTarget				= datistg.DWH_COUNTERPARTIES;                                                                                                                                                                                                                  
%Let _dsFxTrace			= datiLkp._ListFunzioni;                                                                                                                                                                                                                      
%Let dsMTD					= prvmeta.DWH_tassonomia_controlli;                                                                                                                                                                                                              
%Let dataProvider		= DWH;                                                                                                                                                                                                                                       
%Let _dsFxCampiTecn = datiLkp._ListCampiTecnici;                                                                                                                                                                                                                
%Let metaFolder = %UnQuote(&projectFolder.)&slash.02_Metadati&slash.&dataProvider.&slash.Tabledata;                                                                                                                                                             
%hx_public_checklist(checksOutput=work.histChecks);                                                                                                                                                                                                             
*/                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                
