*==================================================================================================                                                                                                                                                             
* Cliente : AMCO SpA                                                                                                                                                                                                                                            
* Office  : CRO Portfolio Managment -> Data Verification                                                                                                                                                                                                        
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Macro name  : hx_run_lookup_rules                                                                                                                                                                                                                             
* Description : Run rules regarding lookup checks                                                                                                                                                                                                               
* Author      : Uriele De Piano Hexe SpA, 05 November 2020                                                                                                                                                                                                      
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* NOTE: Update a standard check tables.                                                                                                                                                                                                                         
*       History check table has been created in autoexec workflow                                                                                                                                                                                               
*       ATTENZIONE!                                                                                                                                                                                                                                             
*         La macro produce sotto la libreria datichk una tabella contenente le stesse righe della tabella                                                                                                                                                       
*					di partenza aggiungendo il campo flag_<idrule>                                                                                                                                                                                                            
*					ATTENZIONE la join avviene per campo idRecord                                                                                                                                                                                                             
*				                                                                                                                                                                                                                                                           
*					Inoltre aggiorna lo storico dei controlli                                                                                                                                                                                                                 
*==================================================================================================                                                                                                                                                             
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_run_lookup_rules(dqListLookup=_null_,libOutDet=work ) / store secure ;                                                                                                                                                                                
	%Local dsLookup tmpStamp dsid lookupMacroName                                                                                                                                                                                                                  
			;                                                                                                                                                                                                                                                            
	%Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                                
	%Put +---[Macro: &sysmacroname.] -------------+;                                                                                                                                                                                                               
	%Put | Run lookup rules 									  	|;                                                                                                                                                                                                                         
	%Put |   2) Lookup list [&dqListLookup.]			|;                                                                                                                                                                                                                  
	%Put |........................................|;                                                                                                                                                                                                               
	%Put | Started at: &tmpStamp.;                                                                                                                                                                                                                                 
	%Put +----------------------------------------+;                                                                                                                                                                                                               
	*-- Estrazione di tutte le garanzie Reali. Vedere tassonomia nella colonna Note Hexe HYDRA                                                                                                                                                                     
				;                                                                                                                                                                                                                                                           
	Data _null_;                                                                                                                                                                                                                                                   
		Attrib dataProvider		Length=$15 	Label="Data Provider"                                                                                                                                                                                                        
					 idTransaction	Length=$25	Label="Id. transaction"                                                                                                                                                                                                          
					 timeStamp			Length=8		Label="Timestamp" format=datetime.                                                                                                                                                                                                  
					 IdAmbito				Length=$15	Label="Id. ambito"                                                                                                                                                                                                                 
					 IdRule					Length=$25	Label="Id. Rule"                                                                                                                                                                                                                    
					 fx_name  			Length=$256	Label="Functio name"                                                                                                                                                                                                              
					 dsRuleLookup		Length=$40	Label="Data containing lookup rules"                                                                                                                                                                                             
					 dsTableData		Length=$80	Label="Source data"                                                                                                                                                                                                               
					 dsTableLookup	Length=$80	Label="Lookup table"                                                                                                                                                                                                             
					 rcLookup				Length=8		Label="Return Code lookup"                                                                                                                                                                                                          
					 msgLookup			Length=$256	Label="Message"                                                                                                                                                                                                                   
					 macro_lookup		Length=$256	Label="Name lookup'macro"                                                                                                                                                                                                       
					 dsDetailsCheck	Length=$40  Label="Dataset Output"                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
					 paramFrom			Length=$40                                                                                                                                                                                                                                    
					 columnFrom			Length=$80					                                                                                                                                                                                                                              
					 paramTo   			Length=$40                                                                                                                                                                                                                                   
					 columnTo				Length=$80                                                                                                                                                                                                                                    
			;                                                                                                                                                                                                                                                            
		Declare hash ht(ordered:'yes');                                                                                                                                                                                                                               
			ht.defineKey("dataProvider","idTransaction","IdAmbito","IdRule","dsTableData");                                                                                                                                                                              
			ht.defineData("dataProvider","idTransaction","timeStamp","IdAmbito","IdRule","fx_name"                                                                                                                                                                       
									 ,"dsTableData","dsTableLookup","rcLookup","msgLookup","dsDetailsCheck");                                                                                                                                                                              
			ht.defineDone();                                                                                                                                                                                                                                             
		timeStamp = datetime();                                                                                                                                                                                                                                       
		*-- Scompone il nome della funzione dai parametri;                                                                                                                                                                                                            
		dsRuleLookup = Symget("dqListLookup");                                                                                                                                                                                                                        
		dsid         = Open(dsRuleLookup);                                                                                                                                                                                                                            
		Do While (Fetch(dsid)=0);                                                                                                                                                                                                                                     
			/*hx_check_lookup_value[garanzia.cod_garanzia vs beni.cod_garanzia]*/                                                                                                                                                                                        
			macro_lookup  = getvarc(dsid,varnum(dsid,"tipoCheck"));                                                                                                                                                                                                      
			dataProvider  = getvarc(dsid,varnum(dsid,"dataProvider"));                                                                                                                                                                                                   
			idTransaction = getvarc(dsid,varnum(dsid,"idTransaction"));                                                                                                                                                                                                  
			idAmbito      = getvarc(dsid,varnum(dsid,"idAmbito"));                                                                                                                                                                                                       
			idRule			  = getvarc(dsid,varnum(dsid,"idRule"));                                                                                                                                                                                                            
			idTransaction = getvarc(dsid,varnum(dsid,"idTransaction"));                                                                                                                                                                                                  
			fx_name       = getvarc(dsid,varnum(dsid,"tipoCheck"));                                                                                                                                                                                                      
			Call Missing(dsTableData,dsTableLookup,rcLookup,msgLookup,dsDetailsCheck);                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
			paramFrom = Scan(Scan(macro_lookup,2,'['),1,' ');                                                                                                                                                                                                            
			paramTo   = Scan(Scan(Scan(macro_lookup,2,'['),3,' '),1,']');                                                                                                                                                                                                
			*-- Verifica esistenza della macro variabile che contiene il nome della tabella pivot;                                                                                                                                                                       
			macroNameFrom = scan(paramFrom,1,'.');                                                                                                                                                                                                                       
			macroNameTo   = scan(paramTo,1,'.');                                                                                                                                                                                                                         
			If Not symexist(macroNameFrom) Then Do;                                                                                                                                                                                                                      
				rcLookup  = 0;                                                                                                                                                                                                                                              
				msgLookup = catx(' ',symget("sysmacroname"),": non è stato dichiarato il parametro",macroNameFrom,"come macro variabile");                                                                                                                                 
			End;                                                                                                                                                                                                                                                         
			Else If Not symexist(macroNameTo) Then Do;                                                                                                                                                                                                                   
				rcLookup  = -1;                                                                                                                                                                                                                                             
				msgLookup = catx(' ',symget("sysmacroname"),": non è stato dichiarato il parametro",macroNameTo,"come macro variabile");                                                                                                                                   
			End;                                                                                                                                                                                                                                                         
			Else Do;                                                                                                                                                                                                                                                     
				dsTableData    =  catx('.',Symget(macroNameFrom),scan(paramFrom,2,'.'));                                                                                                                                                                                    
				dsTableLookup  =  catx('.',Symget(macroNameTo),scan(paramTo,2,'.'));                                                                                                                                                                                        
				rcLookup       =  1;                                                                                                                                                                                                                                        
				msgLookup      = "Try to execute the lookup rule";                                                                                                                                                                                                          
			  dsDetailsCheck = cats("&libOutDet.",'.',idAmbito,"_temp",Compress(translate(idRule,' ','.')));                                                                                                                                                             
                                                                                                                                                                                                                                                                
				*-- Con la prossima sequenza di istruzioni verifico se esiste una precedente tabella nella check area;                                                                                                                                                      
				*-- In questo caso cancella la tabella che verrà ricostruita da questo nuovo giro all interno del ciclo;                                                                                                                                                   
				*-- Do while che richiama la macro di lookup;                                                                                                                                                                                                               
				dsTableDataCheck = catx('.',"datichk",scan(dsTableData,2,'.'));                                                                                                                                                                                             
				If exist(dsTableDataCheck) Then Do;                                                                                                                                                                                                                         
					*-- La Call Execute verrà eseguita subito dopo il passo di data;                                                                                                                                                                                          
					Call Execute(catx(' ',"Proc Sql;Drop Table",dsTableDataCheck,";Quit;"));                                                                                                                                                                                   
				End;                                                                                                                                                                                                                                                        
			End;		                                                                                                                                                                                                                                                       
			rc = ht.add();                                                                                                                                                                                                                                               
		End;                                                                                                                                                                                                                                                          
		dsid = close(dsid);                                                                                                                                                                                                                                           
		rc = ht.output(dataset:"work._lookupTrace");                                                                                                                                                                                                                  
	Run;                                                                                                                                                                                                                                                           
	%Let dsid = %sysfunc(Open(work._lookupTrace));                                                                                                                                                                                                                 
	%Do %While(%sysfunc(fetch(&dsid.))=0);                                                                                                                                                                                                                         
		%*Let macro_lookup = %Bquote(%Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,macro_lookup)))));                                                                                                                                                                
		%Let rcLookup       = %Sysfunc(getvarn(&dsid.,%sysfunc(varnum(&dsid.,rcLookup))));                                                                                                                                                                            
		%Let dsTableData    = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,dsTableData))));                                                                                                                                                                         
		%Let dsTableLookup  = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,dsTableLookup))));                                                                                                                                                                       
		%Let idRule         = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,idRule))));                                                                                                                                                                              
		%Let idRule         = %sysfunc(compress(%Sysfunc(translate(%NrQuote(&idRule.),%NrQuote( ),%NrQuote(.)))));                                                                                                                                                    
		%Let dsDetailsCheck = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,dsDetailsCheck))));                                                                                                                                                                      
		%If &rcLookup.=1 %Then %Do;                                                                                                                                                                                                                                   
		/*                                                                                                                                                                                                                                                            
			%Put dsTableData   = [&dsTableData.];                                                                                                                                                                                                                        
			%Put dsTableLookup = [&dsTableLookup.];                                                                                                                                                                                                                      
			%Put dsDetailsCheck = [&dsDetailsCheck.];                                                                                                                                                                                                                    
			%Put rcLookup      = [&rcLookup.];                                                                                                                                                                                                                           
			%Put idRule				 = [&idRule.];                                                                                                                                                                                                                                
		*/                                                                                                                                                                                                                                                            
			%hx_lookup_value(lookupFrom = %UnQuote(&dsTableData.)                                                                                                                                                                                                        
											,lookupto  	= %UnQuote(&dsTableLookup.)                                                                                                                                                                                                              
											,idRule    	= &idRule.                                                                                                                                                                                                                               
											,dsDetailsChecks = %UnQuote(&dsDetailsCheck.)                                                                                                                                                                                                        
											);                                                                                                                                                                                                                                                   
			*-- Devo capire se sono al primo run oppure no per conservare i flag creati da regole precedenti;                                                                                                                                                            
			%Let dsDetails = datichk.%Qscan(&dsTableData.,2,%NrQuote(.));                                                                                                                                                                                                
			%If %sysfunc(exist(&dsDetails.))=0 %Then %Do;                                                                                                                                                                                                                
				Data &dsDetails.; Set %Qscan(&dsTableData.,1,%NrQuote(.)).%Qscan(&dsTableData.,2,%NrQuote(.));                                                                                                                                                              
				Run;                                                                                                                                                                                                                                                        
			%End;                                                                                                                                                                                                                                                        
			Proc Sort data=%UnQuote(&dsDetails.);                                                                                                                                                                                                                        
				by idRecord;                                                                                                                                                                                                                                                
			Run;                                                                                                                                                                                                                                                         
			Proc Sort data=&dsDetailsCheck.;                                                                                                                                                                                                                             
				by idRecord;                                                                                                                                                                                                                                                
			Run;                                                                                                                                                                                                                                                         
			Data &dsDetails.; Merge &dsDetails. &dsDetailsCheck.(keep=idRecord flgLkp_:);                                                                                                                                                                                
				by idRecord;                                                                                                                                                                                                                                                
			Run;                                                                                                                                                                                                                                                         
			Proc Sql;                                                                                                                                                                                                                                                    
				Drop Table &dsDetailsCheck.; Quit;                                                                                                                                                                                                                          
			Quit;                                                                                                                                                                                                                                                        
		%End;                                                                                                                                                                                                                                                         
	%End;	                                                                                                                                                                                                                                                         
	%Let dsid= %sysfunc(close(&dsid.));                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
	Proc Sql;                                                                                                                                                                                                                                                      
		Create Table NPL_HIST_CHECKS As	                                                                                                                                                                                                                              
			Select * From &histchecks.                                                                                                                                                                                                                                   
			;                                                                                                                                                                                                                                                            
	Quit;                                                                                                                                                                                                                                                          
	%*-- Ultimo step aggiornamento dello storico dei controlli;                                                                                                                                                                                                    
	%Let dsid = %sysfunc(Open(work._lookupTrace));                                                                                                                                                                                                                 
	%Do %While(%sysfunc(fetch(&dsid.))=0);                                                                                                                                                                                                                         
		%Let dsTableData = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,dsTableData))));                                                                                                                                                                            
		%Let provider    = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,dataProvider))));                                                                                                                                                                           
		%Let idRule      = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,idRule))));                                                                                                                                                                                 
		%Let idAmbito    = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,idAmbito))));                                                                                                                                                                               
		%Let fx_name     = %Sysfunc(getvarc(&dsid.,%sysfunc(varnum(&dsid.,fx_name))));                                                                                                                                                                                
		Proc Sql;                                                                                                                                                                                                                                                     
			Delete From &histchecks.                                                                                                                                                                                                                                     
				Where dataProvider  = "&provider."                                                                                                                                                                                                                          
					And idAmbito      = "&idAmbito."                                                                                                                                                                                                                           
					And idTransaction = "&idTrasaction."                                                                                                                                                                                                                       
					And idRule = "&idRule."                                                                                                                                                                                                                                    
					And dta_reference = "&dta_reference."d                                                                                                                                                                                                                     
					;                                                                                                                                                                                                                                                          
		Quit;                                                                                                                                                                                                                                                         
		Data _null_;                                                                                                                                                                                                                                                  
			%*-- Note: nella macro ci sono le valorizzazione di alcuni campi chiave                                                                                                                                                                                      
						1) idTransaction                                                                                                                                                                                                                                          
						2) dataProvider                                                                                                                                                                                                                                           
						3) tableName                                                                                                                                                                                                                                              
					;                                                                                                                                                                                                                                                          
			%hx_declare_ht_hist_check(htTable=&histchecks.);                                                                                                                                                                                                             
			Retain tableName ' ';                                                                                                                                                                                                                                        
			tableName  = Scan(Symget("dsTableData"),2,'.');                                                                                                                                                                                                              
			tableName  = catx('.',"datichk",tableName,scan(,2,'.',));                                                                                                                                                                                                    
			Put tableName=;                                                                                                                                                                                                                                              
			If exist(tableName) Then Do;                                                                                                                                                                                                                                 
				nrecTotal  = hx_get_nobs(tableName);                                                                                                                                                                                                                        
				nvarsTotal = hx_get_nvars(tableName);                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
				idAmbito  = "&idAmbito.";                                                                                                                                                                                                                                   
				descr_ambito = put(idAmbito,$dqambit.);                                                                                                                                                                                                                     
				IdRule    = "&IdRule.";                                                                                                                                                                                                                                     
				descr_rule = put(idRule,$dqrules.);                                                                                                                                                                                                                         
				fx_name	  = "&fx_name.";                                                                                                                                                                                                                                    
				principio = "dominio";                                                                                                                                                                                                                                      
				fieldName = catx('_',"flglkp",compress(translate("&idRule.",' ','.')));                                                                                                                                                                                     
				dsid = Open(tableName);                                                                                                                                                                                                                                     
				tableName = scan(tableName,2,'.'); *-- Nello storico dei controlli non è riportata la libname;                                                                                                                                                             
				Do While (Fetch(dsid)=0);                                                                                                                                                                                                                                   
					%*-- Update Statistics on check missing;                                                                                                                                                                                                                   
					If ht.check(key:idTransaction,key:dataProvider,key:idAmbito,key:idRule,key:tableName,key:fieldName) ^= 0 Then Do;                                                                                                                                          
						nOccurs = ifc(GetvarC(dsid,Varnum(dsid,fieldName))=:'Y',1,0);                                                                                                                                                                                             
						rc 			= ht.add();                                                                                                                                                                                                                                         
	 				End;                                                                                                                                                                                                                                                      
					Else Do;                                                                                                                                                                                                                                                   
						rc      = ht.find(key:idTransaction,key:dataProvider,key:idAmbito,key:idRule,key:tableName,key:fieldName);                                                                                                                                                
						nOccurs = ifc(GetvarC(dsid,Varnum(dsid,fieldName))=:'Y',sum(nOccurs,1),sum(nOccurs,0));                                                                                                                                                                   
						rc			= ht.replace();                                                                                                                                                                                                                                      
					End;                                                                                                                                                                                                                                                       
				End;                                                                                                                                                                                                                                                        
				dsid = Close(dsid);                                                                                                                                                                                                                                         
				rc = ht.output(dataset:"&histchecks.");                                                                                                                                                                                                                     
			End;                                                                                                                                                                                                                                                         
		Run;                                                                                                                                                                                                                                                          
	%End;                                                                                                                                                                                                                                                          
	%Let dsid = %sysfunc(close(&dsid.));                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
	%Uscita:                                                                                                                                                                                                                                                       
		%Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
		%Put +---[Macro: &sysmacroname.] -------------+;                                                                                                                                                                                                              
		%Put | Run lookup rules 									  	|;                                                                                                                                                                                                                        
		%Put |   2) Lookup list [&dqListLookup.]			|;                                                                                                                                                                                                                 
		%Put |........................................|;                                                                                                                                                                                                              
		%Put | Ended at: &tmpStamp.;                                                                                                                                                                                                                                  
		%Put +----------------------------------------+;                                                                                                                                                                                                              
%Mend;                                                                                                                                                                                                                                                          
