*==================================================================================================                                                                                                                                                             
* Cliente : AMCO SpA                                                                                                                                                                                                                                            
* Office  : Data Office                                                                                                                                                                                                                                         
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Macro name  : hx_set_portfolio                                                                                                                                                                                                                                
* Description : Macro updates all dataset records by adding portfolio. This feature needs at least of                                                                                                                                                           
*							  one business key:                                                                                                                                                                                                                                     
*									- Rapporto                                                                                                                                                                                                                                            
*									- Fido                                                                                                                                                                                                                                                
*									- Garanzia / Collateral                                                                                                                                                                                                                               
*									- Asta                                                                                                                                                                                                                                                
* Author      : Uriele De Piano Hexe S.p.A 13 January 2021                                                                                                                                                                                                      
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Parameter:                                                                                                                                                                                                                                                    
*    1) dsName : Business table                                                                                                                                                                                                                                 
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Output                                                                                                                                                                                                                                                        
*		1) dsName	: Business tabel raised with portfolio                                                                                                                                                                                                             
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* NOTE:                                                                                                                                                                                                                                                         
*		Macro based on contents of business table looks for the business key to use to retrieve portfolio                                                                                                                                                            
*		Once extracted the business key to be used, this will be use to join with portfolio's table                                                                                                                                                                  
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* UPDATE HISTORY:                                                                                                                                                                                                                                               
*	.................................................................................................                                                                                                                                                             
*==================================================================================================                                                                                                                                                             
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_set_portfolio (dsName=_null_,_businessKey=_null_) / store secure Des="Retrieve portfolio code";                                                                                                                                                       
	%Local _lkpGroup _tmpStamp _rcCode _msgCode _listBusKeys _meta_dslkp_name_                                                                                                                                                                                     
				 _stagingPortfolio _dsid                                                                                                                                                                                                                                    
			;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
	%let _meta_dslkp_name_ = prvmeta.dwh_lookup_rules;                                                                                                                                                                                                             
	%Let _listBusKeys = %NrQuote(cod_rapporto.cod_fido.cod_garanzia.cod_collateral.cod_asta.ndg_debitore.cod_lotto);                                                                                                                                               
	%Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
	%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                             
	%Put | Retrieve portfolio based on business key																	|;                                                                                                                                                                                             
	%Put | Dataset Name: &dsName.;                                                                                                                                                                                                                                 
	%Put |..........................................................................|;                                                                                                                                                                             
	%Put | Started at : &_tmpStamp.;                                                                                                                                                                                                                               
	%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                             
                                                                                                                                                                                                                                                                
	%Let _rcCode =0;                                                                                                                                                                                                                                               
	%if %sysfunc(exist(&dsName.))=0 %Then %Do;                                                                                                                                                                                                                     
   	%log(level = E, msg = &dsName. not exist!!);                                                                                                                                                                                                                
		%Let _msgCode = %NrQuote(&dsName. not exist!!);                                                                                                                                                                                                               
	 	%goto uscita;                                                                                                                                                                                                                                                
	%end;                                                                                                                                                                                                                                                          
	%*-- Check business keys;                                                                                                                                                                                                                                      
	%If %Upcase(&_businessKey.) = _NULL_ %Then %Do;                                                                                                                                                                                                                
		Data _null_;                                                                                                                                                                                                                                                  
			Attrib _businessKey Length=$40                                                                                                                                                                                                                               
				;                                                                                                                                                                                                                                                           
			_listBusKeys = symget("_listBusKeys");                                                                                                                                                                                                                       
			_dsName      = Symget("dsName");                                                                                                                                                                                                                             
			_dsid 			 = open(_dsName);                                                                                                                                                                                                                                   
			Call Missing(_businessKey);                                                                                                                                                                                                                                  
			_rcBk = count(_listBusKeys,'.')+1;                                                                                                                                                                                                                           
			Do _v=1 To _rcBk until(not missing(_businessKey));                                                                                                                                                                                                           
				_businessKey = scan(_listBusKeys,_v,'.');                                                                                                                                                                                                                   
				If varnum(_dsid,_businessKey)<=0 Then Call Missing(_businessKey);                                                                                                                                                                                           
			End;                                                                                                                                                                                                                                                         
			_dsid = close(_dsid);                                                                                                                                                                                                                                        
			if not missing(_businessKey) Then                                                                                                                                                                                                                            
			Call Symput("_businessKey",Strip(_businessKey));                                                                                                                                                                                                             
		Run;                                                                                                                                                                                                                                                          
	%End;                                                                                                                                                                                                                                                          
	%if %Upcase(&_businessKey.)=_NULL_ %Then %Do;                                                                                                                                                                                                                  
   	%log(level = E, msg = Business keys on &dsName. has NOT been founded!!);                                                                                                                                                                                    
		%Let _msgCode = %NrQuote(Business keys on &dsName. has NOT been founded!!);                                                                                                                                                                                   
	 	%goto uscita;                                                                                                                                                                                                                                                
	%end;                                                                                                                                                                                                                                                          
	%Put &=_businessKey;                                                                                                                                                                                                                                           
	%*-- Business key founded, so next step makes join with portfolio staging;                                                                                                                                                                                     
	%*-- Function retrieves name of portfolio staging;                                                                                                                                                                                                             
	%Let _stagingPortfolio = %sysfunc(fx_get_dsname_outjoin(&_meta_dslkp_name_.,RECON.TABLE,_msgCode));                                                                                                                                                            
	%if %sysfunc(exist(&_stagingPortfolio.))=0 %Then %Do;                                                                                                                                                                                                          
   	%log(level = E, msg = &_stagingPortfolio. not exist!!);                                                                                                                                                                                                     
		%Let _msgCode = %NrQuote(&_stagingPortfolio. not exist!!);                                                                                                                                                                                                    
	 	%goto uscita;                                                                                                                                                                                                                                                
	%end;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
	%*-- Check if business key also exists in staging portfolio data model;                                                                                                                                                                                        
	%Let _dsid   = %sysfunc(open(&_stagingPortfolio.));                                                                                                                                                                                                            
	%Let _rcCode = %sysfunc(varnum(&_dsid.,&_businessKey.));                                                                                                                                                                                                       
	%Let _dsid   = %sysfunc(close(&_dsid.));                                                                                                                                                                                                                       
	%if &_rcCode.<=0 %Then %Do;                                                                                                                                                                                                                                    
   	%log(level = E, msg = &_businessKey. not exists on &_stagingPortfolio.);                                                                                                                                                                                    
		%Let _msgCode = %NrQuote(&_businessKey. not exists on &_stagingPortfolio.);                                                                                                                                                                                   
	 	%goto uscita;                                                                                                                                                                                                                                                
	%end;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
	%Let _nrecInput = %sysfunc(hx_get_nobs(&dsName.));                                                                                                                                                                                                             
	%Let _recoutput = 0;                                                                                                                                                                                                                                           
	Proc Sql;                                                                                                                                                                                                                                                      
		Create Table &_businessKey. As                                                                                                                                                                                                                                
			Select &_businessKey.                                                                                                                                                                                                                                        
						 ,cod_portafoglio_gest                                                                                                                                                                                                                                    
						 ,des_portafoglio_gest                                                                                                                                                                                                                                    
						 ,count(*) as nrec format=commax12.                                                                                                                                                                                                                       
				From &_stagingPortfolio.                                                                                                                                                                                                                                    
				Where &_businessKey. is not null                                                                                                                                                                                                                            
			  Group by 1,2,3                                                                                                                                                                                                                                             
				Order by 1,2                                                                                                                                                                                                                                                
						;                                                                                                                                                                                                                                                         
	Quit;                                                                                                                                                                                                                                                          
	/*                                                                                                                                                                                                                                                             
	%*-- E stato trovato un caso anomalo sulle garanzie, ovvero il codice 00000000011132000001 appartiene a due                                                                                                                                                    
			 Portafogli. E stato segnalato come anomalia per evitare che duplichi i records finali si applica un work-around                                                                                                                                             
			 In attesa di                                                                                                                                                                                                                                                
	  ;                                                                                                                                                                                                                                                            
 	Data &_businessKey.; Set &_businessKey.;                                                                                                                                                                                                                      
		By &_businessKey. cod_portafoglio_gest;                                                                                                                                                                                                                       
		If first.&_businessKey. Then Output;                                                                                                                                                                                                                          
	Run;                                                                                                                                                                                                                                                           
	*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
	Proc Sql;                                                                                                                                                                                                                                                      
		Create Table _joined_table As                                                                                                                                                                                                                                 
			Select dati.*                                                                                                                                                                                                                                                
						 ,case                                                                                                                                                                                                                                                    
						 		when (lkp.&_businessKey. is not null) then lkp.cod_portafoglio_gest                                                                                                                                                                                    
								else "_ND_"                                                                                                                                                                                                                                             
							end as cod_portafoglio_gest                                                                                                                                                                                                                              
						 ,case                                                                                                                                                                                                                                                    
						 		when (lkp.&_businessKey. is not null) then lkp.des_portafoglio_gest                                                                                                                                                                                    
								else "PORTAFOGLIO NON TROVATO"                                                                                                                                                                                                                          
							end as des_portafoglio_gest                                                                                                                                                                                                                              
						 ,case                                                                                                                                                                                                                                                    
						 		when (lkp.&_businessKey. is not null) then 'Y'                                                                                                                                                                                                         
							  else 'N'                                                                                                                                                                                                                                               
						  end as lkpPortfolio "Lookup with Portfolio"                                                                                                                                                                                                             
				From &dsName. as dati Left Join                                                                                                                                                                                                                             
						 &_businessKey. as lkp                                                                                                                                                                                                                                    
					on dati.&_businessKey. = lkp.&_businessKey.                                                                                                                                                                                                                
			;                                                                                                                                                                                                                                                            
		%Let _recoutput = &sqlObs.;                                                                                                                                                                                                                                   
	Quit;                                                                                                                                                                                                                                                          
	%if &_nrecInput. ne &_recoutput. %Then %Do;                                                                                                                                                                                                                    
   	%log(level = E, msg = The join between &dsName. and &_stagingPortfolio. produced different records);                                                                                                                                                        
		%Let _msgCode = %NrQuote(The join between &dsName. and &_stagingPortfolio. produced different records [&_nrecInput.] vs [&_recoutput.]);                                                                                                                      
	 	%*goto uscita;                                                                                                                                                                                                                                               
	%end;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
	Data &dsName.; Set _joined_table;                                                                                                                                                                                                                              
	Run;                                                                                                                                                                                                                                                           
	%if &syserr.<=4 %Then %Do;                                                                                                                                                                                                                                     
		%Let _rcCode = 1;                                                                                                                                                                                                                                             
	%end;                                                                                                                                                                                                                                                          
	Proc Delete data=_joined_table; Run;                                                                                                                                                                                                                           
	Proc Delete data=&_businessKey.; Run;                                                                                                                                                                                                                          
	%Uscita:                                                                                                                                                                                                                                                       
		%Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                              
		%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                            
		%Put | Retrieve portfolio based on business key																	|;                                                                                                                                                                                            
		%Put | Dataset Name: &dsName.;                                                                                                                                                                                                                                
		%Put |..........................................................................|;                                                                                                                                                                            
		%Put | Ended at : &_tmpStamp.;                                                                                                                                                                                                                                
		%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                            
		Data _null_;                                                                                                                                                                                                                                                  
			%*-- Declare hash table regarding process trace;                                                                                                                                                                                                             
			%hx_declare_ht_pr(htTable=&processTrace.);                                                                                                                                                                                                                   
			sourceCode    = symget("sysmacroname");                                                                                                                                                                                                                      
			stepCode      = catx(' ',"Aggancio del Portafoglio tramite",symget("_businessKey"));                                                                                                                                                                         
			rcCode			  = symget("_rcCode");                                                                                                                                                                                                                              
			msgCode				= symget("_msgCode");                                                                                                                                                                                                                             
			if rcCode=1 Then msgCode = catx(' ',"Sono stati arricchiti su [&dsName.]"                                                                                                                                                                                    
																				 ,put(hx_get_nobs("&dsName"),commax18.)                                                                                                                                                                                                     
																			   ,"records");                                                                                                                                                                                                                              
			rc = ht.add();                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
			%*-- Check all records has been matched;                                                                                                                                                                                                                     
			if rcCode=1 Then Do;                                                                                                                                                                                                                                         
				dsid = open(catx(' ',Symget("dsName"),"(Where=(lkpPortfolio='N'))"));                                                                                                                                                                                       
				nrecord = 0;                                                                                                                                                                                                                                                
				do while (fetch(dsid)=0);                                                                                                                                                                                                                                   
					nrecord = sum(nrecord,1);                                                                                                                                                                                                                                  
				end;                                                                                                                                                                                                                                                        
				dsid = close(dsid);                                                                                                                                                                                                                                         
				Put nrecord=;                                                                                                                                                                                                                                               
				if nrecord>0 Then Do;                                                                                                                                                                                                                                       
					rcCode = 2;                                                                                                                                                                                                                                                
					msgCode = catx(' ',"WARNING!! Ci sono",put(nrecord,commax12.),"chiavi che non sono stati agganciati al Portafoglio");                                                                                                                                      
					timeStamp = datetime();                                                                                                                                                                                                                                    
					rc = ht.add();                                                                                                                                                                                                                                             
				end;                                                                                                                                                                                                                                                        
			end;                                                                                                                                                                                                                                                         
			rc = ht.output(dataset:"&processTrace.");                                                                                                                                                                                                                    
		Run;                                                                                                                                                                                                                                                          
		%If &_rcCode.=1 %Then %Do;                                                                                                                                                                                                                                    
			%hx_update_tabletrace(%Qscan(&dsName.,1,.)                                                                                                                                                                                                                   
														,lkp-portfolio                                                                                                                                                                                                                                    
														,whrcl=%NrQuote(Upcase%(memname%)="%Upcase(%Qscan(&dsName.,2,.))")                                                                                                                                                                                
							);                                                                                                                                                                                                                                                       
		%End;                                                                                                                                                                                                                                                         
%Mend;                                                                                                                                                                                                                                                          
