*==================================================================================================                                                                                                                                                             
* Cliente : AMCO SpA                                                                                                                                                                                                                                            
* Office  : Data Office                                                                                                                                                                                                                                         
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Macro name  : hx_set_portfolio_ldt                                                                                                                                                                                                                            
* Description : Macro updates all dataset records by adding portfolio. This feature needs at least of                                                                                                                                                           
*							  one business key:                                                                                                                                                                                                                                     
*									- Rapporto                                                                                                                                                                                                                                            
*									- Fido                                                                                                                                                                                                                                                
*									- Garanzia / Collateral                                                                                                                                                                                                                               
*									- Asta                                                                                                                                                                                                                                                
* Author      : Uriele De Piano Hexe S.p.A 13 January 2021                                                                                                                                                                                                      
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Parameter:                                                                                                                                                                                                                                                    
*    1) dsName : Business table                                                                                                                                                                                                                                 
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* Output                                                                                                                                                                                                                                                        
*		1) dsName	: Business tabel raised with portfolio                                                                                                                                                                                                             
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* NOTE:                                                                                                                                                                                                                                                         
*		Macro based on contents of business table looks for the business key to use to retrieve portfolio                                                                                                                                                            
*		Once extracted the business key to be used, this will be use to join with portfolio's table                                                                                                                                                                  
* -------------------------------------------------------------------------------------------------                                                                                                                                                             
* UPDATE HISTORY:                                                                                                                                                                                                                                               
*	.................................................................................................                                                                                                                                                             
*==================================================================================================                                                                                                                                                             
;                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                
%Macro hx_set_portfolio_ldt (dsName=_null_) / store secure Des="Force portfolio code";                                                                                                                                                                          
	%Local _tmpStamp _rcCode _msgCode                                                                                                                                                                                                                              
			;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
	%Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
	%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                             
	%Put | Force portfolio code based on dataProvider macro													|;                                                                                                                                                                                         
	%Put | Dataset Name: &dsName.;                                                                                                                                                                                                                                 
	%Put |..........................................................................|;                                                                                                                                                                             
	%Put | Started at : &_tmpStamp.;                                                                                                                                                                                                                               
	%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                             
	Data &dsName.; Set &dsName.;                                                                                                                                                                                                                                   
			Attrib cod_portafoglio_gest Length=$5                                                                                                                                                                                                                        
						 des_portafoglio_gest Length=$255                                                                                                                                                                                                                         
					;                                                                                                                                                                                                                                                          
			Retain cod_portafoglio_gest "%Upcase(&dataProvider.)"                                                                                                                                                                                                        
						 des_portafoglio_gest "&dataProvider.";                                                                                                                                                                                                                   
	Run;                                                                                                                                                                                                                                                           
	%Let _rcCode  = &syserr.;                                                                                                                                                                                                                                      
	%Let _msgCode = %sysfunc(sysmsg());                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
	%Uscita:                                                                                                                                                                                                                                                       
		%Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                              
		%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                            
		%Put | Force portfolio code based on dataProvider macro													|;                                                                                                                                                                                        
		%Put | Dataset Name: &dsName.;                                                                                                                                                                                                                                
		%Put |..........................................................................|;                                                                                                                                                                            
		%Put | Started at : &_tmpStamp.;                                                                                                                                                                                                                              
		%Put +--[Macro name: &sysmacroname.]--------------------------------------------+;                                                                                                                                                                            
		Data _null_;                                                                                                                                                                                                                                                  
			%*-- Declare hash table regarding process trace;                                                                                                                                                                                                             
			%hx_declare_ht_pr(htTable=&processTrace.);                                                                                                                                                                                                                   
			sourceCode    = symget("sysmacroname");                                                                                                                                                                                                                      
			stepCode      = catx(' ',"Force portfolio for &dataProvider: &dsName.");                                                                                                                                                                                     
			rcCode			  = symget("_rcCode");                                                                                                                                                                                                                              
			msgCode				= symget("_msgCode");                                                                                                                                                                                                                             
			if rcCode<=4 Then msgCode = catx(' ',"Sono stati arricchiti su [&dsName.]"                                                                                                                                                                                   
																				 ,put(hx_get_nobs("&dsName"),commax18.)                                                                                                                                                                                                     
																			   ,"records");                                                                                                                                                                                                                              
			rc = ht.add();                                                                                                                                                                                                                                               
			rc = ht.output(dataset:"&processTrace.");                                                                                                                                                                                                                    
		Run;                                                                                                                                                                                                                                                          
		%If &_rcCode.=1 %Then %Do;                                                                                                                                                                                                                                    
			%hx_update_tabletrace(%Qscan(&dsName.,1,.)                                                                                                                                                                                                                   
														,lkp-portfolio                                                                                                                                                                                                                                    
														,whrcl=%NrQuote(Upcase%(memname%)="%Upcase(%Qscan(&dsName.,2,.))")                                                                                                                                                                                
							);                                                                                                                                                                                                                                                       
		%End;                                                                                                                                                                                                                                                         
%Mend;                                                                                                                                                                                                                                                          
