/*{                                                                                                                                                                                                                                                             
	"Descrizione": "Macro che controlla gli rc automatici di sas e manda in errore se superano l'error_level indicato in input.",                                                                                                                                  
	"Parametri": [                                                                                                                                                                                                                                                 
		{ "error_level": "Numero che indica il limite entro il quale il return code non indica errore (default: 4)." },                                                                                                                                               
		{ "msg": "Messaggio di errore generale che viene scritto nel log." }                                                                                                                                                                                          
	],                                                                                                                                                                                                                                                             
	"Return": "void: non restituisce alcun valore.",                                                                                                                                                                                                               
	"Esempio": "<code>%check_rc;",                                                                                                                                                                                                                                 
	"Autore": "Hexe S.p.A.",                                                                                                                                                                                                                                       
	"Sito web": "<http://www.hexeitalia.com>",                                                                                                                                                                                                                     
	"Email": "<info@hexeitalia.com>",                                                                                                                                                                                                                              
	"Manutentori": [ "Hexe S.p.A." ]                                                                                                                                                                                                                               
}*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
%macro check_rc(error_level=4, msg=&syserrortext. ) / store secure ;                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
    %if %symexist(SQLXRC) %then %do;                                                                                                                                                                                                                            
        %if &SQLXRC > &error_level. %then %do;                                                                                                                                                                                                                  
	      %log(level=E, msg=Errore SQL STEP %bquote(&msg.));                                                                                                                                                                                                       
       %end;                                                                                                                                                                                                                                                    
    %end;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
    %if %symexist(SQLRC) %then %do;                                                                                                                                                                                                                             
        %if &SQLRC > &error_level. %then %do;                                                                                                                                                                                                                   
	      %log(level=E, msg=Errore SQL STEP %bquote(&msg.));                                                                                                                                                                                                       
       %end;                                                                                                                                                                                                                                                    
    %end;                                                                                                                                                                                                                                                       
	                                                                                                                                                                                                                                                               
    %if &syserr > &error_level. %then %do;                                                                                                                                                                                                                      
	      %log(level=E, msg=Errore DATA%str(/)PROC STEP %bquote(&msg.));                                                                                                                                                                                           
    %end;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
%mend check_rc;                                                                                                                                                                                                                                                 
