/*{                                                                                                                                                                                                                                                             
	"Descrizione": "Macro che crea un dataset vuoto leggendone le caratteristiche e la struttura (variabili, constraint, pk) da un metadato (dataset sas)).",                                                                                                      
	"Parametri": [                                                                                                                                                                                                                                                 
		{ "dsMtd": "Nome del metadato." },                                                                                                                                                                                                                            
		{ "whrClause": "Clausola di where (di default estrae tutti i record)." },                                                                                                                                                                                     
        { "dsOut": "Nome della tabella di output. Passare questo parametro solo se nel metadato è presente una sola tabella da creare oppure se si utilizza una where che estrae una sola tabella." },                                                         
	],                                                                                                                                                                                                                                                             
    "Struttura del metadato": [                                                                                                                                                                                                                                 
        { "MEMNAME": "Nome tabella" },                                                                                                                                                                                                                          
        { "VARNAME": "Nome della variabile" },                                                                                                                                                                                                                  
        { "TYPE": "Tipo variabile [char(len)|num]" },                                                                                                                                                                                                           
        { "LABEL": "Label variabile [opzionale]" },                                                                                                                                                                                                             
        { "FORMAT": "Formato variabile [opzionale]" },                                                                                                                                                                                                          
        { "INFORMAT": "Informat variabile [opzionale]" },                                                                                                                                                                                                       
        { "NULL": "Indica se costruire la constraint not null oppure no. Valori accettati: [not null|<vuoto>]"},                                                                                                                                                
        { "PK": "Flag che indica se la variabile sulla riga deve essere utilizzata per costruire la primary key. Valori accettati: [1=>(True)|0=>(False)]" }                                                                                                    
    ],                                                                                                                                                                                                                                                          
	"Return": "void: non restituisce alcun valore.",                                                                                                                                                                                                               
	"Esempio": "<code>%create_dset_struct_from_mtd(tabella_mtd);",                                                                                                                                                                                                 
	"Autore": "Hexe S.p.A.",                                                                                                                                                                                                                                       
	"Sito web": "<http://www.hexeitalia.com>",                                                                                                                                                                                                                     
	"Email": "<info@hexeitalia.com>",                                                                                                                                                                                                                              
	"Manutentori": [ "Hexe S.p.A." ]                                                                                                                                                                                                                               
}*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
%macro create_dset_struct_from_mtd(dsMtd, whrClause=1, dsOut=_null_ ) / store secure ;                                                                                                                                                                          
                                                                                                                                                                                                                                                                
    %local                                                                                                                                                                                                                                                      
        _dsid _i _pk_name _previuos_memname                                                                                                                                                                                                                     
        _memname _varname _type _varnum _format                                                                                                                                                                                                                 
        _informat  _null _pk                                                                                                                                                                                                                                    
        __memname __format __informat __label __pk                                                                                                                                                                                                              
    ;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
    %let _i = 1;                                                                                                                                                                                                                                                
    %let _pk_name = pk;                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
    %* Apro e leggo il metadato;                                                                                                                                                                                                                                
    %let _dsid = %sysfunc(open(&dsMtd. (where=(%unquote(&whrClause.)))));                                                                                                                                                                                       
    %let _rc = %sysfunc(fetch(&_dsid.));                                                                                                                                                                                                                        
    %* Ciclo sul metadato riga per riga;                                                                                                                                                                                                                        
    %do %while(&_rc.=0);                                                                                                                                                                                                                                        
        %* Recupero le informazioni sulla struttura della tabella dal metadato;                                                                                                                                                                                 
        %let _previuos_memname = &_memname.;                                                                                                                                                                                                                    
        %let _memname = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., MEMNAME))));                                                                                                                                                                         
        %let _varname = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., VARNAME))));                                                                                                                                                                         
        %let _type = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., TYPE))));                                                                                                                                                                               
        %let _type = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., TYPE))));                                                                                                                                                                               
        %let _label = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., LABEL))));                                                                                                                                                                             
        %let _varnum = &_i.;                                                                                                                                                                                                                                    
        %let _format = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., FORMAT))));                                                                                                                                                                           
        %let _informat = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., INFORMAT))));                                                                                                                                                                       
        %let _null = %sysfunc(getvarc(&_dsid., %sysfunc(varnum(&_dsid., NULL))));                                                                                                                                                                               
        %let _pk = %sysfunc(getvarn(&_dsid., %sysfunc(varnum(&_dsid., PK))));                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
        %if %bquote(&dsOut.) = _null_ %then %let __memname = &_memname.;                                                                                                                                                                                        
        %else %let __memname = &dsOut.;                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
        %* Controllo che nel campo NULL ci siano esclusivamente i valori accettati [not null|<vuoto>] altrimenti setto a vuoto con Warning;                                                                                                                     
        %if %qupcase(&_null.) ne %str(NOT NULL) and %bquote(&_null.) ne %str() %then %do;                                                                                                                                                                       
            %log(level = W, msg = Il valore %bquote(&_null.) non è accettabile. Viene sovrascritto con <vuoto> e non viene creata la constraint sulla colonna &_varname.);                                                                                     
            %let _null = %str();                                                                                                                                                                                                                                
        %end;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
        %* Controllo che nel campo PK ci siano esclusivamente i valori accettati [1|0] altrimenti mando in errore;                                                                                                                                              
        %if %bquote(&_pk.) ne 1 and %bquote(&_pk.) ne 0 %then %do;                                                                                                                                                                                              
            %log(level = E, msg = Il valore %bquote(&_pk.) non è accettabile. Valori accettati: [1|0]);                                                                                                                                                        
            %return;                                                                                                                                                                                                                                            
        %end;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
        %* Compongo lo statement per il format se presente nel metadato per il campo in lettura;                                                                                                                                                                
        %if %is_empty(%bquote(&_format.)) %then %let __format = &_format.;                                                                                                                                                                                      
        %else %let __format = format=&_format.;                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                
        %* Compongo lo statement per informat se presente nel metadato per il campo in lettura;                                                                                                                                                                 
        %if %is_empty(%bquote(&_informat.)) %then %let __informat = &_informat.;                                                                                                                                                                                
        %else %let __informat = informat=&_informat.;                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
        %* Compongo lo statement per label se presente nel metadato per il campo in lettura;                                                                                                                                                                    
        %if %is_empty(%bquote(&_label.)) %then %let __label = &_label.;                                                                                                                                                                                         
        %else %let __label = label="&_label.";                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
        %* Compongo lo statement per creare le primary key;                                                                                                                                                                                                     
        %if %sysevalf(&_pk., boolean) %then %do;                                                                                                                                                                                                                
            %if %is_empty(%bquote(&__pk.)) %then %let __pk = &__pk. &_varname.;                                                                                                                                                                                 
            %else %let __pk = &__pk., &_varname.;                                                                                                                                                                                                               
            %let _pk_name = &_pk_name._&_varname.;                                                                                                                                                                                                              
        %end;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
        %if &_i. = 1 %then %do;                                                                                                                                                                                                                                 
            proc sql;                                                                                                                                                                                                                                           
            create table &__memname. %str(%()                                                                                                                                                                                                                   
                &_varname. &_type. &__format. &__informat. &__label. &_null.                                                                                                                                                                                    
        %end;                                                                                                                                                                                                                                                   
        %else %do;                                                                                                                                                                                                                                              
                ,&_varname. &_type. &__format. &__informat. &__label. &_null.                                                                                                                                                                                   
        %end;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
        %let _rc = %sysfunc(fetch(&_dsid.));                                                                                                                                                                                                                    
        %**                                                                                                                                                                                                                                                     
        * Se il nome della tabella da creare è cambiato rispetto al precedente o siamo a fine lettura (_rc della fetch = -1)                                                                                                                                   
        * allora chiudo sql e ne verrà aperto uno nuovo per la creazione della tabella successiva;                                                                                                                                                             
        %if %bquote(&_previuos_memname.) ne %bquote(&_memname.) or %sysevalf(&_rc. = -1, boolean) %then %do;                                                                                                                                                    
                %if %length(&_pk_name.) >32 %then %let _pk_name = _pk_0001_;                                                                                                                                                                                    
                %if %bquote(&_pk_name.) ne pk %then %do;                                                                                                                                                                                                        
                    ,constraint &_pk_name. primary key(&__pk.)                                                                                                                                                                                                  
                %end;                                                                                                                                                                                                                                           
            );                                                                                                                                                                                                                                                  
            quit;                                                                                                                                                                                                                                               
            %let _i = 0;                                                                                                                                                                                                                                        
        %end;                                                                                                                                                                                                                                                   
        %let _i = %eval(&_i.+1);                                                                                                                                                                                                                                
    %end;                                                                                                                                                                                                                                                       
    %let _dsid = %sysfunc(close(&_dsid.));                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                
%mend create_dset_struct_from_mtd;                                                                                                                                                                                                                              
