/*{                                                                                                                                                                                                                                                             
	"Descrizione": "Copy any file from one folder to another",                                                                                                                                                                                                     
	"Parametri": [                                                                                                                                                                                                                                                 
		{ "folderFrom": "From folder" },                                                                                                                                                                                                                              
		{ "folderTo"  : "To folder" },                                                                                                                                                                                                                                
        { "file"      : "Filename" },                                                                                                                                                                                                                           
	],                                                                                                                                                                                                                                                             
	"Return": "Macro variabile named hx_copy_file",                                                                                                                                                                                                                
	"Autore": "Hexe S.p.A.",                                                                                                                                                                                                                                       
	"Sito web": "<http://www.hexeitalia.com>",                                                                                                                                                                                                                     
	"Email": "<info@hexeitalia.com>",                                                                                                                                                                                                                              
	"Manutentori": [ "Hexe S.p.A." ]                                                                                                                                                                                                                               
}*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
%macro hx_copy_file (folderFrom=_null_,folderTo=_null_,file=_null_,fileDest=_null_ ) / store secure ;                                                                                                                                                           
  %Local _tmpStamp                                                                                                                                                                                                                                              
	;                                                                                                                                                                                                                                                              
  %Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                              
  %Put +---[Macro: &sysmacroname.] -----------------+;                                                                                                                                                                                                          
  %Put | Copy file.					        	    |;                                                                                                                                                                                                                         
  %Put | Filename	    : &file.					|;                                                                                                                                                                                                                           
  %Put | From folder    : &folderFrom.				|;                                                                                                                                                                                                                    
  %Put | To folder      : &folderTo.				|;                                                                                                                                                                                                                      
  %Put | Filename dest  : &fileDest.				|;                                                                                                                                                                                                                      
  %Put |............................................|;                                                                                                                                                                                                          
  %Put | Started at: &_tmpStamp.;                                                                                                                                                                                                                               
  %Put +--------------------------------------------+;                                                                                                                                                                                                          
  Data _null_;                                                                                                                                                                                                                                                  
    Attrib rc_copy  Length=$200                                                                                                                                                                                                                                 
           fileDest Length=$255                                                                                                                                                                                                                                 
       ;                                                                                                                                                                                                                                                        
    folderFrom = "&folderFrom.";                                                                                                                                                                                                                                
    file       = "&file.";                                                                                                                                                                                                                                      
    folderTo   = "&folderTo.";                                                                                                                                                                                                                                  
    if fileExist(catx("&slash.",folderFrom,file))=0 then                                                                                                                                                                                                        
      rc_copy = catx(' ',"ERROR: file",file,"not exists in folder",folderFrom,". Application of checks will be stopped");                                                                                                                                       
    else if fileExist(folderTo)=0 then                                                                                                                                                                                                                          
      rc_copy = catx(' ',"ERROR: destination folder",folderTo,"not exists. Application of checks will be stopped");                                                                                                                                             
    else do;                                                                                                                                                                                                                                                    
      %If %Upcase(&fileDest.)=_NULL_ %Then %Do;                                                                                                                                                                                                                 
        fileDest = strip(file);                                                                                                                                                                                                                                 
      %End;                                                                                                                                                                                                                                                     
      %Else %Do;                                                                                                                                                                                                                                                
	    fileDest = Strip("&fileDest.")||'.'||Strip(Scan(file,1,'.','b'));                                                                                                                                                                                          
      %End;                                                                                                                                                                                                                                                     
      _cmdCopy = 'copy "'||strip(folderFrom)||"&slash."||strip(file)||'" "'||Strip(folderTo)||"&slash."||Strip(fileDest)||'"';                                                                                                                                  
      rc       = system(_cmdCopy);                                                                                                                                                                                                                              
	  Put rc= _cmdCopy=;                                                                                                                                                                                                                                           
	  rc_copy  = ifc(rc=0,"File was copied!","File was not copied!");                                                                                                                                                                                              
    end;                                                                                                                                                                                                                                                        
    Call SymputX("hx_copy_file",rc_copy,'G');                                                                                                                                                                                                                   
  Run;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
  %Put &=hx_copy_file;                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
  %Uscita:                                                                                                                                                                                                                                                      
    %Let _tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                            
    %Put +---[Macro: &sysmacroname.] ---------------+;                                                                                                                                                                                                          
    %Put | Copy file.					        	|;                                                                                                                                                                                                                           
    %Put | Filename	: &file.					    |;                                                                                                                                                                                                                         
    %Put | From folder: &folderFrom.				|;                                                                                                                                                                                                                      
    %Put | To folder  : &folderTo.				    |;                                                                                                                                                                                                                    
    %Put | Filename dest  : &fileDest.				|;                                                                                                                                                                                                                    
    %Put |..........................................|;                                                                                                                                                                                                          
    %Put | Ended at: &_tmpStamp.;                                                                                                                                                                                                                               
    %Put +------------------------------------------+;                                                                                                                                                                                                          
%mend;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
