                                                                                                                                                                                                                                                                
%Macro hx_get_fx_package ( ) / store secure ;                                                                                                                                                                                                                   
	%let fxName 		 	 = %sysfunc(dequote(&fxName.));                                                                                                                                                                                                                
	%let fxLibname 		 = %sysfunc(dequote(&fxLibname.));                                                                                                                                                                                                            
	%Let fxPackageList = %sysfunc(dequote(&fxPackageList.));                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
 	%Put +--[Macro: &sysmacroname.] --------------------------------+;                                                                                                                                                                                            
 	%Put | &=fxName;                                                                                                                                                                                                                                              
 	%Put | &=fxLibname;                                                                                                                                                                                                                                           
 	%Put | &=fxPackageList;                                                                                                                                                                                                                                       
 	%Put +----------------------------------------------------------+;                                                                                                                                                                                            
 	Data _null_;                                                                                                                                                                                                                                                  
		Attrib fxLibname 	Length=$10                                                                                                                                                                                                                                  
					 fxName			Length=$100                                                                                                                                                                                                                                      
					 packLib		Length=$10                                                                                                                                                                                                                                       
					 wclClause	Length=$256                                                                                                                                                                                                                                     
					 fxPackage	Length=$100                                                                                                                                                                                                                                     
					 flgCheckFx Length=$1                                                                                                                                                                                                                                      
					 package		Length=$256                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                
				;                                                                                                                                                                                                                                                           
		declare hash htPack(ordered:'yes',multidata:'yes');                                                                                                                                                                                                           
			htPack.defineKey("fxName");                                                                                                                                                                                                                                  
			htPack.defineData("fxName","fxPackage","package");                                                                                                                                                                                                           
			htPack.defineDone();                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
		fxLibname = strip(symget("fxLibname"));                                                                                                                                                                                                                       
		fxName		= strip(symget("fxName"));                                                                                                                                                                                                                            
		If libref(fxLibname)=0 Then Do;                                                                                                                                                                                                                               
			wclClause = cats("Upcase(libname)='",Upcase(fxLibname),"' And Upcase(memname) not in ('RUN_MACRO_FUNCTION')");                                                                                                                                               
			dsid = open(catx(' ',"sashelp.vtable (Where=(",wclClause,"))"));                                                                                                                                                                                             
			Do While (Fetch(dsid)=0);                                                                                                                                                                                                                                    
				fxPackage = GetvarC(dsid,Varnum(dsid,"MEMNAME"));                                                                                                                                                                                                           
				packLib	  = GetvarC(dsid,Varnum(dsid,"LIBNAME"));                                                                                                                                                                                                           
				dsPack 		= Open(catx('.',packLib,fxPackage));                                                                                                                                                                                                               
				flgCheckFx = 'N';                                                                                                                                                                                                                                           
				Do While (Fetch(dsPack)=0 And flgCheckFx='N');                                                                                                                                                                                                              
					package 	 = Getvarc(dsPack,Varnum(dsPack,"_Key_"));                                                                                                                                                                                                        
					flgCheckFx = ifc(prxmatch(cats('/',fxName,"/i"),package)>0,'Y','N');                                                                                                                                                                                       
				End;                                                                                                                                                                                                                                                        
				If flgCheckFx='Y' Then Do;                                                                                                                                                                                                                                  
					fxPackage = dsname(dsPack);                                                                                                                                                                                                                                
					rc = htPack.add();                                                                                                                                                                                                                                         
				End;                                                                                                                                                                                                                                                        
				dsPack = Close(dsPack);                                                                                                                                                                                                                                     
			End;                                                                                                                                                                                                                                                         
			dsid = close(dsid);                                                                                                                                                                                                                                          
		End;                                                                                                                                                                                                                                                          
		rc = htPack.output(dataset:"&fxPackageList.");                                                                                                                                                                                                                
	Run;                                                                                                                                                                                                                                                           
%Mend;                                                                                                                                                                                                                                                          
