/*{                                                                                                                                                                                                                                                             
	"Descrizione": "Estrazione delle varaibili di tabelle presenti all interno di una libname SAS",                                                                                                                                                                
	"Parametri": [                                                                                                                                                                                                                                                 
	  { "dsLibname": "Nome della libname" },                                                                                                                                                                                                                       
    { "dsListDataModel": "Nome della tabella contenente i data model di ogni singola tabella" },                                                                                                                                                                
	],                                                                                                                                                                                                                                                             
	"Return": [                                                                                                                                                                                                                                                    
  	{ "dsListDataModel": "Output del data model" }                                                                                                                                                                                                               
  ],                                                                                                                                                                                                                                                            
	"Esempio": "",                                                                                                                                                                                                                                                 
	"Autore": "Hexe S.p.A.",                                                                                                                                                                                                                                       
	"Sito web": "<http://www.hexeitalia.com>",                                                                                                                                                                                                                     
	"Email": "<info@hexeitalia.com>",                                                                                                                                                                                                                              
	"Manutentori": [ "Hexe S.p.A." ]                                                                                                                                                                                                                               
}*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
%Macro hx_get_list_columns(dsLibname=_null_,dsListDataModel=hx_get_list_columns ) / store secure ;                                                                                                                                                              
  %local tmpStamp                                                                                                                                                                                                                                               
     ;                                                                                                                                                                                                                                                          
  %Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
  %Put +---[Macro: &sysmacroname.] ----------------------------------------------------;                                                                                                                                                                        
  %Put | Libname &dsLibname.;                                                                                                                                                                                                                                   
  %Put |...............................................................................;                                                                                                                                                                        
  %Put | Starting at: &tmpStamp.;                                                                                                                                                                                                                               
  %Put +-------------------------------------------------------------------------------;                                                                                                                                                                        
                                                                                                                                                                                                                                                                
  %if %sysfunc(exist(&dsListDataModel.)) %then %do;                                                                                                                                                                                                             
    proc delete data=&dsListDataModel.; Run;                                                                                                                                                                                                                    
  %end;                                                                                                                                                                                                                                                         
  ods results off;                                                                                                                                                                                                                                              
  ods output variables=&dsListDataModel. (where=(lowcase(variable) not in ("dbcontainer","idrecord","idtransaction","tablename",'#')));                                                                                                                         
     proc datasets lib=&dsLibname. memtype=data;                                                                                                                                                                                                                
        contents data=_all_;                                                                                                                                                                                                                                    
     run;                                                                                                                                                                                                                                                       
     quit;                                                                                                                                                                                                                                                      
  ods output close;                                                                                                                                                                                                                                             
  ods results on;                                                                                                                                                                                                                                               
  Data &dsListDataModel.; Set &dsListDataModel.;                                                                                                                                                                                                                
    Attrib tableAlias Length=$80;                                                                                                                                                                                                                               
    Drop _:                                                                                                                                                                                                                                                     
	  ;                                                                                                                                                                                                                                                            
    _rc = count(member,'_');                                                                                                                                                                                                                                    
    Call Missing(tableAlias);                                                                                                                                                                                                                                   
    Do _i=1 To _rc;                                                                                                                                                                                                                                             
      tableAlias = catx('_',tableAlias,scan(scan(member,2,'.'),_i,'_'));                                                                                                                                                                                        
    End;                                                                                                                                                                                                                                                        
  Run;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
  %Let tmpStamp = %sysfunc(putn(%sysfunc(datetime()),datetime.));                                                                                                                                                                                               
  %Put +---[Macro: &sysmacroname.] ----------------------------------------------------;                                                                                                                                                                        
  %Put | Libname &dsLibname.;                                                                                                                                                                                                                                   
  %Put |...............................................................................;                                                                                                                                                                        
  %Put | Ended at: &tmpStamp.;                                                                                                                                                                                                                                  
  %Put +-------------------------------------------------------------------------------;                                                                                                                                                                        
%Mend;                                                                                                                                                                                                                                                          
