/*{                                                                                                                                                                                                                                                             
    "title": "log.sas",                                                                                                                                                                                                                                         
    "desc": "Macrofunzione che scrive messaggi nel log.",                                                                                                                                                                                                       
    "params": [                                                                                                                                                                                                                                                 
        { "level": "Livello del messaggio: (N)ote, (W)arning, (E)rror (N è il defualt). Se il livello di messaggio è E e esiste una macrovariabile globale debug_mode=1 effettua l'ABORT della sessione." },                                                  
        { "msg": "Messaggio da scrivere nel log." },                                                                                                                                                                                                            
		{ "returnCode": "Codice di ritorno in caso di ABORT. Il default è 255 e non deve superare questo numero." },                                                                                                                                                 
		{ "debug": "Booleano (1-True o 0-False) che indica se mandare in ABORT (se 1) in caso di level=E." }                                                                                                                                                          
    ],                                                                                                                                                                                                                                                          
    "return": "void: Non restituisce alcun valore.",                                                                                                                                                                                                            
    "example": "%log(level = W, msg = Attenzione! C'è un problema non bloccante!)",                                                                                                                                                                            
    "author": "Hexe S.p.A.",                                                                                                                                                                                                                                    
    "website": "http://www.hexeitalia.com",                                                                                                                                                                                                                     
	"email": "<info@hexeitalia.com>",                                                                                                                                                                                                                              
	"mantainers": [ "Hexe S.p.A." ]                                                                                                                                                                                                                                
}*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
%macro log(level=N, msg=, returnCode=255, debug=&debug_mode.) / store secure ;                                                                                                                                                                                 
                                                                                                                                                                                                                                                                
	%local _msg _pre _debug_mode;                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
	%let _pre = %bquote([Hexe]:);                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
	%if &level. = N %then %let _msg = NOTE: &_pre. %bquote(&msg.);                                                                                                                                                                                                 
	%else %if &level. = W %then %let _msg = WARNING: &_pre. %bquote(&msg.);                                                                                                                                                                                        
	%else %if &level. = E %then %let _msg = ERROR: &_pre. %bquote(&msg.);                                                                                                                                                                                          
	%else %let _msg = %bquote(&msg.);                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                
	%put &_msg.;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                
	%if %symexist(debug_mode) %then %let _debug_mode = &debug_mode.;                                                                                                                                                                                               
	%else %let _debug_mode = 1;                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                
	%if &level.=E and &_debug_mode.=0 %then %do;                                                                                                                                                                                                                   
		data _null_;                                                                                                                                                                                                                                                  
			abort return &returnCode.;                                                                                                                                                                                                                                   
		run;                                                                                                                                                                                                                                                          
	%end;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
%mend log;                                                                                                                                                                                                                                                      
