/*{                                                                                                                                                                                                                                                             
	"Descrizione": "Macro che setta dinamicamente macrovariabili globali inserite in un metadato specifico (Colonne obbligatorie: [VAR, VAL]).",                                                                                                                   
	"Parametri": [                                                                                                                                                                                                                                                 
		{ "dset": "Nome del dataset metadato contenente le macrovariabili da settare." },                                                                                                                                                                             
		{ "whr_clause": "Clausola di where da applicare in fase di estrazione del metadato di input." }                                                                                                                                                               
	],                                                                                                                                                                                                                                                             
	"Return": "void: non ritorna alcun valore.",                                                                                                                                                                                                                   
	"Esempio": "<code>%set_params(mtd_params);",                                                                                                                                                                                                                   
	"Autore": "Hexe S.p.A.",                                                                                                                                                                                                                                       
	"Sito web": "<http://www.hexeitalia.com>",                                                                                                                                                                                                                     
	"Email": "<info@hexeitalia.com>",                                                                                                                                                                                                                              
	"Manutentori": [ "Hexe S.p.A." ]                                                                                                                                                                                                                               
}*/                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
%macro set_params(dset, whr_clause=1 ) / store secure ;                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                
	%if %sysfunc(exist(&dset., DATA)) = 0 %then %do;                                                                                                                                                                                                               
		%log(level = E, msg = Dataset &dset. does not exist in macrofunction &sysmacroname..);                                                                                                                                                                        
		%return;                                                                                                                                                                                                                                                      
	%end;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                
	data _null_;                                                                                                                                                                                                                                                   
		set &dset. (where=(%unquote(&whr_clause.)));                                                                                                                                                                                                                  
		call symputx(var, val, 'G');                                                                                                                                                                                                                                  
	run;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
%mend set_params;                                                                                                                                                                                                                                               
